### ISSUE TITLE
Curso DataCamp: Introduction to Natural Language Processing in Python

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#102]
Curso DataCamp: Introduction to Natural Language Processing in Python

https://www.datacamp.com/courses/introduction-to-natural-language-processing-in-python

**Comment by piantino** [comment]
Procurar um curso que use a mesma stack que já trabalhamos.

**Comment by nanipumpkin** [comment]
[intro_nlp.pdf](https://github.com/saibrotech/mentoria/files/10568575/intro_nlp.pdf)
