### ISSUE TITLE
Adicionar Tech Talk LinkedIn no YouTube

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#105]
Passos para concluir a tarefa:

- [x]  download da gravação;
- [x]  edição do vídeo;
- [x]  exportação do vídeo editado;
- [x]  criação de thumbnail;
- [x]  upload para o YouTube;
- [x]  preenchimento de metadados;
- [x]  postagem;
- [x]  divulgação do link no linkedin.

**Comment by piantino** [comment]
Resultado da atividade:

https://youtu.be/BkHkHFi12IY

https://www.linkedin.com/feed/update/urn:li:activity:6999441338433720320?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A6999441338433720320%29
