### ISSUE TITLE
Escolher curso de React/Next

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#106]
- https://www.cod3r.com.br/courses/nextjs
- https://www.udemy.com/course/react-redux-profissional/
- https://www.udemy.com/course/nextjs-react-the-complete-guide/

**Comment by isabelahyeda** [comment]
Curso escolhido: https://www.udemy.com/course/react-do-zero-a-maestria-c-hooks-router-api-projetos/

**Comment by piantino** [comment]
@isabelahyeda agora crie uma nova com o checklist dos tópicos tratados e vincule com essa atividade.

**Comment by isabelahyeda** [comment]
Criada issue com o conteúdo do curso listado e carga horária #109
