### ISSUE TITLE
React do Zero a Maestria (c/ hooks, router, API, Projetos)

### ISSUE THREAD

**Issue by isabelahyeda** [saibrotech/mentoria#109]
https://www.udemy.com/course/react-do-zero-a-maestria-c-hooks-router-api-projetos/

Duração total: 29h 50m.

Conteúdo do curso:

- [x] Introdução
- [x] Fundamentos do React
- [x] Avançando em React
- [x] React e CSS
- [x] Formulários com React
- [x] Projeto: Secret Word
- [x] Requisições HTTP com React
- [x] React Router
- [x] Context API do React
- [x] Projeto MiniBlog (React Router, Hooks, Context, Firebase, Autenticação)
- [x] Entenda os Hooks do React
- [x] Projeto ReactGram (React, Redux, Express, MongoDB, Mongoose e mais)
- [x] Apêndice A: JavaScript Moderno
- [x] Apêndice B: Introdução a APIs
- [x] Apêndice C: Setup do TypeScript
- [x] Apêndice D: React com TypeScript
- [x] Apêndice E: Projeto de React com TypeScript
- [x] Apêndice F: Projeto em React com a API do TMDB
- [x] Conclusão e próximos passos
- [x] Adicionar certificado no LinkedIn

**Comment by isabelahyeda** [comment]
![Image](https://user-images.githubusercontent.com/98404083/221553908-436ed310-38b5-476e-b79a-b246311749ad.png)

**Comment by piantino** [comment]
@isabelahyeda parabéns. 
Não esqueça de colocar o certificado no LinkedIn,  adicionei um item na lista de atividades da tarefa.

**Comment by isabelahyeda** [comment]
@piantino Obrigada. Feito.
