### ISSUE TITLE
Desafio RocketNews

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#11]
Desenvolva uma página para captação de leads ou newsletter.

https://efficient-sloth-d85.notion.site/Desafio-RocketNews-2e2c5d56b41f4b13a7d8df6b5affc0ec

https://ivancarlosjr.github.io/rocketseat-discover/desafios/desafio-rocketnews/rocketnews.html

**Comment by piantino** [comment]
Melhorias após revisão:

- [ ] Usar variáveis declaradas no css
- [ ] Organizar os seletores css, primeiro os elementos e depois as classes.

**Comment by piantino** [comment]
@IvanCarlosJr ajustar as variáveis e testar.

**Comment by IvanCarlosJr** [comment]
correções feitas @gutivalente 


![Image](https://user-images.githubusercontent.com/110834695/191333607-7c4377bd-6670-4f7f-9d34-cb6b845520ab.png)

variáveis aplicadas, funcionando corretamente.

**Comment by gutivalente** [comment]
@IvanCarlosJr mais algumas coisinhas pra ajeitar:
- [ ] Mudar cursor para "pointer" quando estiver em cima do botão de enviar.
- [ ] Fazer com que o div com a classe "conteudo" pare de gerar esse scroll vertical desnecessário na página.

**Comment by IvanCarlosJr** [comment]
@gutivalente, correções aplicadas 

https://ivancarlosjr.github.io/rocketseat-discover/desafios/desafio-rocketnews/rocketnews.html

**Comment by gutivalente** [comment]
@IvanCarlosJr tudo ok!
