### ISSUE TITLE
Editar e publicar Tech Talk de React e Nextjs no Youtube

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#116]
Tech talk:
https://github.com/saibrotech/mentoria/issues/70

Passos para concluir a tarefa:

- [x]  download da gravação;
- [x]  edição do vídeo;
- [x]  exportação do vídeo editado;
- [x]  criação de thumbnail;
- [x]  upload para o YouTube;
- [x]  preenchimento de metadados;
- [x]  postagem;
- [x]  divulgação do link no linkedin.

Tarefa concluída. Resultado em: https://www.youtube.com/watch?v=vE4NL4bQCzc

**Comment by AndreBuitoni** [comment]
Atrasei que foi uma beleza, mas essa semana finalizado essa! 😱

**Comment by AndreBuitoni** [comment]
FINALIZADO
https://www.youtube.com/watch?v=vE4NL4bQCzc

**Comment by piantino** [comment]
Ficou show!
