### ISSUE TITLE
Tentar Badge CSS

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#119]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/css/css-quiz.md

Usar extensão para tradução rápida:
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?hl=en

**Comment by IvanCarlosJr** [comment]
![Image](https://user-images.githubusercontent.com/110834695/229638816-840c3e08-d17b-4a97-8e6e-f262bbf32f75.png)

**Comment by piantino** [comment]
Parabéns Ivan!
