### ISSUE TITLE
Fazer trilha "Especializar" da Rocketseat

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#12]
https://app.rocketseat.com.br/discover/trails/especializar

### Módulos

- [x] JavaScript assíncrono e Promises
- [x] Trabalhando com APIs
- [x] Fundamentos do ReactJS
- [x] Fundamentos do Typescript
- [x] Github para times
- [x] Transition e Animation
- [x] SQL avançado

### Compartilhar Conquistas

- [x] Publicar certificado no LinkedIn e compartilhar em um Post
- [x] Compartilhar conquista no canal "compartilhe" do discord

**Comment by IvanCarlosJr** [comment]
https://www.linkedin.com/posts/ivan-carlos-duarte-junior_certificado-trilha-especializar-do-discover-activity-7023664113172004864-kE3U?utm_source=share&utm_medium=member_desktop
