### ISSUE TITLE
Fazer Curso de React.Js e Next.Js

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#120]
https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/

Repositório: https://github.com/IvanCarlosJr/curso-react

92,5 horas de vídeo sob demanda
29 artigos

Módulos introdutórios: 

- [x] Introdução 
- [x] React (O Básico)
- [x] Mock Service Worker e testes para <Home /> (Testes avançados)
- [x] Reack Hooks (Teoria e hooks avançados)
- [x] Roteamento com React Router Dom v5 (Básico)
- [x] React Router Dom v6
- [x] Projeto 1: Landing pages com Strapi e PostgreSQL (Back-end)
- [ ] Projeto 1: Landing pages com React (Front-end)
- [ ] Projeto 1: Landing pages - Deploy (Strapi v4)

Módulos avançados, com Next.Js: 

- #147 

Módulos Bônus: 

- [ ] HTML5 e CSS3 (Para iniciantes) - Bônus 
- [ ] Landing Page com HTML5 e CSS3 - Bônus
- [x] JavaScript Essencial - Bônus 
- [ ] TypeScript Essencial - Bônus
- [ ] #EXTRA - Comandos Linux/Unix mais usados - Aprender a navegar no terminal - Bônus

Conclusão: 

- [ ] Conclusão e certificado

**Comment by piantino** [comment]
@IvanCarlosJr , pretende continuar esse curso nesse ano?

**Comment by IvanCarlosJr** [comment]
Esse ano não pretendo, @piantino

**Comment by piantino** [comment]
Obrigado pelo retorno Ivan.
Vou encerrar essa atividade para liberar espaço no nosso Board.
