### ISSUE TITLE
Fazer Seção 15 do Curso Web Dev Udemy

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#121]
Seção 15 - Boss Level Challenge 2 - The Simon Game

- [x] 186 - What You'll Make: The Simon Game
- [x] 187 - Play The Game
- [x] 188 - Step 0: Download the Starting Files
- [x] 189 - Step 1: Add Javascript and jQuery
- [x] 190 - Step 1: Answer
- [x] 191 - Step 2: Create a New Pattern
- [x] 192 - Step 2: Answer
- [x] 193 - Step 3: Show the Sequence to the User with Animations and Sounds
- [x] 194 - Step 3: Answer
- [x] 195 - Step 4: Check Which Button is Pressed
- [x] 196 - Step 4: Answer
- [x] 197 - Step 5: Add Sounds to Button Clicks
- [x] 198 - Step 5: Answer
- [x] 199 - Step 6: Add Animations to User Clicks
- [x] 200 - Step 6: Answer
- [x] 201 - Step 7: Start the Game
- [x] 202 - Step 7: Answer
- [x] 203 - Step 8: Check the User's Answer Against the Game Sequence
- [x] 204 - Step 8: Answer
- [x] 205 - Step 9: Game Over
- [x] 206 - Step 9: Answer
- [x] 207 - Step 10: Restart the Game
- [x] 208 - Step 10: Answer
- [x] 209 - Download the Completed Project Code
- [x] 210 - Tip From Angela: Dealing With Frustration
- [x] Postar resultado prático, se houver.

**Comment by AndreBuitoni** [comment]
LINK PARA O JOGO FINALIZADO
https://andrebuitoni.github.io/Web-Development/simon-game/index.html

![Image](https://user-images.githubusercontent.com/68255266/215573668-ec51548f-dedb-47ae-a2a6-0e504d2da318.png)


JAVASCRIPT PARTE 1

![Image](https://user-images.githubusercontent.com/68255266/215574230-3a3d1ece-641f-414c-92c9-503caac3a3a9.png)

JAVASCRIPT PARTE 2

![Image](https://user-images.githubusercontent.com/68255266/215574453-7e1e000c-7ca2-4ddd-bd4d-f37ed67a392e.png)

COMENTÁRIOS

Não consegui seguir o passo-a-passo da professora Angela Yu. No final acabei vendo alguns vídeos no YouTube sobre esse jogo e entendi parcialmente a lógica dos códigos. Meu aproveitamento nesse desafio foi baixo.

**Comment by piantino** [comment]
O @AndreBuitoni me mostrou outro projeto e consegui avaliar que o conhecimento atual dele já é maior do que o utilizado nesse projeto.
