### ISSUE TITLE
Fazer curso de Next.js

### ISSUE THREAD

**Issue by gutivalente** [saibrotech/mentoria#123]
https://www.udemy.com/course/nextjs-react-the-complete-guide/

- [x] Section 8: Adding Backend Code with API Routes (Fullstack React)
- [x] Section 9: Project Time: API Routes
- [ ] Section 10: Working with App-wide State (React Context)
- [ ] Section 11: Complete App Example: Build a Full Blog A to Z
- [ ] Section 12: Deploying NextJS Apps
- [ ] Section 13: Adding Authentication
- [ ] Section 14: Optional: NextJS Summary
- [ ] Section 15: Course Roundup

**Comment by piantino** [comment]
@gutivalente estou encerrando essa atividade do nosso board.
