### ISSUE TITLE
Fazer curso de Next.js - Optimizing NextJS Apps

### ISSUE THREAD

**Issue by gutivalente** [saibrotech/mentoria#126]
- [x] Section 1: Getting Started
- [x] Section 2: Optional: React Refresher
- [x] Section 3: Pages & File-based Routing
- [x] Section 4: Project Time: Working with File-based Routing
- [x] Section 5: Page Pre-Rendering & Data Fetching
- [x] Section 6: Project Time: Page Pre-Rendering & Data Fetching
- [x] Section 7: Optimizing NextJS Apps

**Comment by piantino** [comment]
@gutivalente está colocando isso em um repositório no Github?

**Comment by gutivalente** [comment]
@piantino não estou, mas o professor disponibiliza um repositório com várias branches, cada uma sendo de um momento diferente do curso. Por exemplo, [essa branch é a que tem até a seção 7 completa](https://github.com/mschwarzmueller/nextjs-course-code/tree/07-api-routes-starting-project).
