### ISSUE TITLE
Realizar Curso Programação Fullstack Samsung Ocean

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#128]
https://oceanbrasil.com/atividades/3058-Jornada-FullStack

Este curso é dividido em 8 aulas de 3 horas cada. Totalizando 24 horas de curso.

--------------------------------------------------------------
DESCRIÇAO DO CURSO
--------------------------------------------------------------

Sobre a atividade
A JORNADA FULL STACK SERÁ OFERECIDA DE FORMA INTENSIVA ENTRE 02 E 24 DE FEVEREIRO

Nessa Jornada você terá a oportunidade de aprender backend e frontend e colocar os conhecimentos em prática em um projeto completo que será desenvolvido ao longo das 8 aulas!

- 02/02/2023: Backend com NodeJs e Express (Parte 1) - 09h00 às 12h00 (Brasília)
- 03/02/2023: Backend com NodeJs e Express (Parte 2) - 09h00 às 12h00 (Brasília)
- 09/02/2023: Laboratório de Backend com Banco de Dados e MongoDB - 09h00 às 12h00 (Brasília)
- 10/02/2023: Integrando os serviços de backend na nuvem - 09h00 às 12h00 (Brasília)
- 16/02/2023: Frontend Web com ReactJS: Introdução (Parte 1) - 09h00 às 12h00 (Brasília)
- 17/02/2023: Frontend Web com ReactJS: Introdução (Parte 2) - 09h00 às 12h00 (Brasília)
- 23/02/2023: Frontend Web com ReactJS: Integração com Backend (Parte 1) - 09h00 às 12h00 (Brasília)
- 24/02/2023: Frontend Web com ReactJS: Integração com Backend (Parte 2) - 09h00 às 12h00 (Brasília)

O que irá aprender
EMENTA - BACKEND

Entenda de uma vez por todas o que é backend e quais são as tecnologias envolvidas nesse pedaço tão importante de um software, responsável pela maior parte do processamento de informações e por proteger a camada de banco de dados da aplicação. Você entenderá desde os princípios do backend, tendo uma introdução completa sobre o assunto e começará a dar os primeiros passos desenvolvendo uma aplicação em NodeJS, com a linguagem de programação JavaScript.

Tópicos:

- O que exatamente é backend?
- Evolução do Backend
- REST (Verbos de comunicação: GET, POST, PUT, DELETE)
- JSON
- Postman (Criando/fazendo requisições e organizando em collections)
- JSON Viewer
- JavaScript: do frontend para o backend
- NodeJS
- Package Json
- NPM (Node Package Manager)
- Benchmarking
- Criação do projeto
- Início do desenvolvimento da aplicação CRUD
-> Create, Read (All/Single), Update & Delete
-> Criar, Ler (Tudo ou Individual), Atualizar e Remover
- Node Express
- Body-Parser

EMENTA - FRONTEND

Aprenda a construir um site utilizando a tecnologia ReactJS, com a linguagem de programação JavaScript e combinando HTML e CSS. O React é uma biblioteca mantida pelo Facebook e Instagram, de código aberto e utilizada amplamente por diversos sites, como Netflix, Imgur, Airbnb, entre outros.
- Criando o projeto
- Configurando o VSCode
- Familiarizando com JavaScript
- Implementando o React
- Entendendo os componentes
- Criando a primeira página
- Implementando componentes interativos
- Ferramentas de desenvolvedores: Inspecionar elementos
- Qual a responsabilidade do Frontend?
- Avançando no ReactJS
- Construção de mais páginas para compor a aplicação
- Integrando com uma aplicação backend

--------------------------------------------------------------
LINKS DA AULA
--------------------------------------------------------------

Repositório da aula, no GitHub
https://github.com/paulosalvatore/ocean-jornada-fullstack-fevereiro-23

Miro:
https://miro.com/app/board/uXjVPr-4uM0=/?share_link_id=152694689598

GitHub Paulo Salvatore
https://github.com/paulosalvatore

Site do Paulo Salvatore
https://paulosalvatore.com.br

Discord do Paulo Salvatore
https://discord.com/invite/BRjMwnCmfk

Playlist Backend - Canal PauloSalvatore
https://www.youtube.com/playlist?list=PLzFYWfRVHp5Jx-iNLxhUydXwnYPqmV2MU

Preparação para as trilhas
https://github.com/paulosalvatore/samsung-ocean-preparacao-trilhas

Preparação para backend
https://github.com/paulosalvatore/samsung-ocean-preparacao-trilhas/raw/main/Samsung%20Ocean%20-%20Prepara%C3%A7%C3%A3o%20(Trilha%20Backend).pdf

GitPod
https://gitpod.io/#https://github.com/paulosalvatore/nodejs-clean-template

--------------------------------------------------------------
HISTÓRICO DAS AULAS (8 AULAS)
--------------------------------------------------------------

- [x] AULA 1 - Conceitos iniciais, preparação do ambiente, criação dos arquivos iniciais (3h)
- [x] AULA 2 - Métodos HTTP, criação de endpoints e outros (3h)
- [x] AULA 3 - Criação do Banco de Dados com o MongoDB, inserção de dados no banco (3h)
- [x] AULA 4 - Integrando os serviços de backend na nuvem  (3h)
- [x] AULA 5 - Criação do Projeto Frontend com VITE e REACT (3h)
- [x] AULA 6 - Criação dos componentes REACT para o APP (3h)
- [x] AULA 7 - Frontend Web com ReactJS: Integração com Backend (Parte 1)
- [x] AULA 8 - Frontend Web com ReactJS: Integração com Backend (Parte 2)
- [x] Postar Resultado Prático, se houver.

**Comment by AndreBuitoni** [comment]
Tela do Projeto onde aparecem cards inseridos no banco de dados
![Image](https://user-images.githubusercontent.com/68255266/225387951-ceb821fd-254b-401b-aada-cb8c1beb7a0a.png)

**Comment by AndreBuitoni** [comment]
As imagens do projeto vieram de uma API pública d Rick and Morty
![Image](https://user-images.githubusercontent.com/68255266/225388609-c5699bc6-6382-42b0-850a-556cf8d5f84e.png)

**Comment by PaulaBuitoni** [comment]
https://github.com/PaulaBuitoni/curso-fullstack-ocean
