### ISSUE TITLE
Conversa sobre Currículo

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#129]
Tirar dúvidas sobre:
* Status atual como programador/suporte (resumo);
* Como titular a experiência na SaibroTech;
* Estrutura do currículo.

**Comment by piantino** [comment]
Foi combinado que iremos marcar eventos para análise do CV do Ivan:

- [ ] Analisar o LinkedIn
- [ ] Analisar CV suporte
- [ ] Analisar CV Front-end

**Comment by IvanCarlosJr** [comment]
Planilha de vagas enviadas: 
https://docs.google.com/spreadsheets/d/1eWJrrWZuvX7s-DRJhqVTQHlVcJKd5y4UKKui4SwWZoQ/edit?usp=sharing

**Comment by piantino** [comment]
Aumentar conexões no LinkedIn (37) focando em recrutadores em Florianópolis e região.
Procurar em empresas de TI:

- https://scinova.com.br/sc-tem-12-empresas-na-lista-das-melhores-de-ti-para-trabalhar-no-brasil/
- https://www.acate.com.br/vagas/
- https://www.acate.com.br/associados/
- https://celta.certi.org.br/graduadas/

**Comment by IvanCarlosJr** [comment]
Currículo Front-end

[curriculo-ivan-carlos-dev.pdf](https://github.com/saibrotech/mentoria/files/11023428/curriculo-ivan-carlos-dev.pdf)

**Comment by piantino** [comment]
Criado atividade [#149](https://github.com/saibrotech/mentoria/issues/149) para as melhorias levantadas.
