### ISSUE TITLE
Processo seletivo FIESC - Técnico de Suporte de TI - Júnior

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#130]
https://fiesc.pandape.infojobs.com.br/Detail/329506

Técnico de Suporte de TI - Júnior

- Florianópolis -SC
- Presencial
- Efetivo - CLT
- Período integral 

Processo: 

- [x] Recebimento de currículos
- [x] Avaliação Teórica
- [x] Análise Curricular
- [x] Análise Documental
- [x] Avaliação Prática Individual
- [x] Etapa Coletiva
- [x] Resultado Final

**Comment by IvanCarlosJr** [comment]
Segue a relação dos candidatos aprovados:

1 - Adriel Oliveira
2 - João Vitor Oliveira De Brum
3 - Christian Mattos Moreira
4 - Ivan Carlos Duarte Junior
5 - Luiz Alexandre Siridakis
6 - Erick Dias

**Comment by piantino** [comment]
@IvanCarlosJr parabéns pelo resultado nesse que foi um dos seus primeiros processos seletivos em TI.
Coloque em review para marcarmos uma conversa sobre os seus pontos fortes e fracos nesse processo.

**Comment by piantino** [comment]
Na conversa ficou resolvido que continuará a buscar vagas para suporte e front-end e a fazer curso de programação.
