### ISSUE TITLE
Fazer Seções 17, 18 e 19 do Curso WebDeb Udemy

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#131]
Seção 17 - Backend Web Development

- [x] 217. Backend Web Development Explained

Seção 18 - Node.js

- [x] 218. What is Node.js ?
- [x] 219. Install Node.js on Mac
- [x] 220. Install Node.js on Windows
- [x] 221. The Power of the Command Line and How to Use Node
- [x] 222. The Node REPL (Read Evaluation Print Loops)
- [x] 223. How to Use the Native Node Modules
- [x] 224. The NPM Package Manager and Installing External Node Modules
- [x] 225. Tip From Angela - Step Up to the Challenge
- [x] Postar Resultado Prático, se houver.

Seção 19 - Express.js with Node.js

- [x] 226. What is Express?
- [x] 227. Creating Our First Server With Express
- [x] 228. Handling Requests and Responses: the GET Request
- [x] 229. Nodemon Installation
- [x] 230. Understanding and Working with Routes
- [x] 231. What We'll Make: A Calculator
- [x] 232. Calculator Setup Challenge
- [x] 233. Calculator Setup: Challenge Solution
- [x] 234. Responding to Requests with HTML Files
- [x] 235. Processing Post Requests with Body Parser
- [x] 236. BMI Routing Challenge
- [x] 237. Solution to the BMI Routing Challenge
- [x] 238. Tip From Angela - How to Solidify Your Knowledge
- [x] Postar Resultado Prático, se houver.

**Comment by AndreBuitoni** [comment]
Seção 17 - Backend Web Development
Seção 18 - Node.js

Foram seções mais teóricas, sem resultado prático.

Seção 19 - EXPRESS.JS with NODE.JS

Aprendi o que é o Express e como incorporar ele no nosso projeto.
Instalei o nodemon para atualizar automaticamente o servidor ao realizar mudanças no código.
Instalei o Body Parser para poder acessar os dados enviados pelo usuário no formulário.

Ao final dessa seção, construí uma calculadora de IMC que roda no backend.
![Image](https://user-images.githubusercontent.com/68255266/218569348-3d91ae55-8f17-4863-a9a1-af8951653ca3.png)

**Comment by piantino** [comment]
@AndreBuitoni faltou o link do repositório com a calculadora, último item do check list.

**Comment by piantino** [comment]
Não houve resultado prático.
