### ISSUE TITLE
Processo Seletivo Sebrae-RS

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#133]
[Link Vaga](https://sebrae-rs.gupy.io/jobs/3990362?jobBoardSource=gupy_opportunities)
- [x] Currículo
- [x] Triagem
- [x] Teste de Conhecimentos
- [x] Entrevista Individual
- [x] Avaliação de Perfil
- [x] Final

**Comment by piantino** [comment]
Parabéns Nani pela conquista da vaga!
