### ISSUE TITLE
Trilha Data Science - DataCamp

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#134]
[Link para a trilha](https://app.datacamp.com/learn/career-tracks/data-scientist-with-python?version=7)
- [x] 1. Introduction to Python
- [x] 2. Intermediate Python
- [x] 3. PROJECT: Investigating Netflix Movies and Guest Stars in the Office
- [x] 4. Data Manipulation with pandas
- [x] 5. Joining Data with pandas
- [x] 6. Introduction to Statistics in Python
- [x] 7. The GitHub History of the Scala Language
- [x] 8. Introduction to Data Visualization with Matplotlib
- [x] 9. Introduction to Data Visualization with Seaborn
- [x] 10. Introduction to NumPy
- [x] 11. Python Data Science Toolbox (Part 1)
- [x] 12. PROJECT: The Android App Market on Google Play
- [x] 13. Python Data Science Toolbox (Part 2)
- [x] 14. Intermediate Data Visualization with Seaborn
- [x] 15. Data Communication Concepts
- [x] 16. Project: A Visual History of Nobel Prize Winners
- [x] 17. SKILL ASSESSMENT: Data Manipulation with Python
- [x] 18. Introduction to Importing Data in Python
- [x] 19. Intermediate Importing Data in Python
- [x] 20. Cleaning Data in Python
- [x] 21. Working with Dates and Times in Python
- [x] 22. SKILL ASSESSMENT: Importing and Cleaning Data with Python
- [x] 23. Writing Functions in Python
- [x] 24. SKILL ASSESSMENT: Python Programming
- [x] 25. Exploratory Data Analysis in Python
- [x] 26. Analyzing Police Activity with pandas
- [x] 27. Introduction to Regression with statsmodels in Python
- [x] 28. Sampling in Python
- [x] 29. Hypothesis Testing in Python
- [x] 30. PROJECT: Dr. Semmelweis and the Discovery of Handwashing
- [x] 31. Supervised Learning with scikit learn
- [x] 32. PROJECT: Predicting Credit Card Approvals
- [x] 33. Unsupervised Learning in Python
- [x] 34. Machine Learning with Tree-Based Models in Python

**Comment by nanipumpkin** [comment]
[link para o certificado](https://www.datacamp.com/statement-of-accomplishment/track/8ae1c2babb2dff6ef903329e920d1a78ab5588a8?raw=1)

**Comment by piantino** [comment]
Muito bom @nanipumpkin , vi que já colocou no LinkedIn também!
