### ISSUE TITLE
Certificação Profissional Data Science

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#135]

**Comment by piantino** [comment]
Olá @nanipumpkin estou organizando as atividades do projeto.
Ainda tem acesso ao Datacamp, vai continuar essa formação?

**Comment by nanipumpkin** [comment]
Oi @piantino!  Perdi o  timing de fazer essa prova. Minha assinatura acabou em maio, então não tenho previsão de quando poderei fazer.
