### ISSUE TITLE
Adicionar o SouJunior no LinkedIn e na SaibroTech

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#136]
- [x] Tarefa: Avaliar o perfils da galera do SouJunior
- [x] Alinhar como ficará no LinkedIn, qual o cargo utilizado, etc...

**Comment by piantino** [comment]
@nanipumpkin veja se pode participar na sexta dia 24/02 às 14hrs, conforme evento no discord.

**Comment by isabelahyeda** [comment]
![Image](https://user-images.githubusercontent.com/98404083/221185382-6e1103a1-bf8f-49dd-b2bb-bb6c6003e5d3.png)

**Comment by isabelahyeda** [comment]
![Image](https://user-images.githubusercontent.com/98404083/221186193-509e567d-d205-46ed-bf00-77073bd649db.png)

**Comment by isabelahyeda** [comment]
![Image](https://user-images.githubusercontent.com/98404083/221186477-f889a68e-3197-42f9-9f87-2f8350d6d340.png)

**Comment by piantino** [comment]
Definições:

- Manter a experiência profissional na SaibroTech, como Aprendiz.
- Adicionar link do projeto de vagas na experiência da SaibroTech.
- Adicionar voluntariado na SouJunior.

**Comment by piantino** [comment]
Fizemos as alterações em conjunto:

@piantino 

![Image](https://user-images.githubusercontent.com/737364/221505517-7066b3d2-97b7-4ce1-9db9-3f8379c2b4dc.png)

@nanipumpkin 

![Image](https://user-images.githubusercontent.com/737364/221505904-e5c1c91d-7357-4a70-b496-af76d4bad136.png)
