### ISSUE TITLE
Assistir ao Curso de Autenticação com Passport.js (YouTube)

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#140]
<h1>Passport JS User Authentication</h1>
11 aulas

Course Link:
[Click Me](https://www.youtube.com/playlist?list=PLYQSCk-qyTW2ewJ05f_GKHtTIzjynDgjK)

This series has two Github repositories associated with it.  Click the below links to view the code you see in the video.
[Pasta do Github Express Session Authentication Starter](https://github.com/zachgoll/express-session-authentication-starter)
[Pasta do Github Express JWT Authentication Starter](https://github.com/zachgoll/express-jwt-authentication-starter)

---

Vídeo-Aulas

- [x] 1. What is User Authentication? (Node + Express + Passport) ----------------------------28/02/2023
- [x] 2. HTTP Headers and Cookies -------------------------------------------------------------------""------
- [x] 3. Your Complete Guide to Understanding the Express session library ------------------------""------
- [x] 4. What is express middleware and how does it work?
- [ ] 5. Passport Local Configuration (Node + Passport + Express)
- [ ] 6. Passport Local Strategy usage (Node + Passport + Express)
- [ ] 7. A Crash Course in Public Key Cryptography (a.k.a. Asymmetric Cryptography)
- [ ] 8. Deriving, Signing, and Verifying a JWT (JSON Web Token)
- [ ] 9.  Passport JWT Strategy Flow (Node + Passport + Express)
- [ ] 10. Passport JWT Strategy Configuration (Node + Passport + Express)
- [ ] 11. How to use the Passport JWT Strategy with Angular

---

Outros links relevantes

[Passport.js Website](https://www.passportjs.org/)
[Site do Miro com o Mapa Mental das Aulas](https://miro.com/app/board/uXjVPm4V8aw=/)

**Comment by piantino** [comment]
@AndreBuitoni eu usei o Auth0 como backend de autenticação:

https://github.com/piantino/alura-nextjs-course/blob/main/pages/api/auth/%5B...auth0%5D.js

Ele é gratuíto até certo ponto:
https://auth0.com/pricing

**Comment by AndreBuitoni** [comment]
Beleza, salvei os links aqui para quando eu for voltar pra essa parte de login. Essa tarefa eu vou encerrar porque vou descontinuar esse curso.
