### ISSUE TITLE
Curso React.Js e Next.Js Part2

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#147]
https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/

Repositório: https://github.com/IvanCarlosJr/curso-react

92,5 horas de vídeo sob demanda
29 artigos

Módulos introdutórios: 

- #120 

Módulos avançados, com Next.Js:

- [ ] Next.Js com SSR, SSG e ISR (ou ISG)
- [ ] Migrando o Next.js para TypeScript
- [ ] Usando create-next-app com --example
- [ ] Projeto 2: Blog - Back-end com Strapi 
- [ ] GraphQL Queries com Strapi 
- [ ] Projeto 2: Blog - Front-end com Next.js (e React)
- [ ] Autenticação de usuários com Strapi 
- [ ] GraphQL Mutations com Strapi (depende da seção anterior) 
- [ ] Autenticação de usuários com Next.js e NextAuth.js

**Comment by piantino** [comment]
Como o curso não será feito esse ano, estou encerrando para deixar o Board organizado:
https://github.com/saibrotech/mentoria/issues/120
