### ISSUE TITLE
Fazer seção 22 do curso WebDev Udemy (Angela Yu)

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#148]
Seção 22 - EJS

- [x] 263 - What we'll make: a TO DO list ----- ----- ----- ----- ----- ----- ----- 16/03/2023
- [x] 264 - Linter Errors with EJS
- [x] 265 - Templates? Why do we need templates? ----- ----- ----- ----- ----- 21/03/2023
- [x] 266 - Creating your first EJS template
- [x] 267 - Running Code inside the EJS Template
- [x] 268 - Passing Data from your Webpage to your Server
- [x] 269 - The Concept of Scope in the context of Javascript
- [x] 270 - Adding Pre-made CSS Stylesheets to your website
- [x] 271 - Understanding templates vs layouts
- [x] 272 - Understanding node module exports: How to pass functions and data between files
- [x] 273 - Tip From Angela - Use Accountability in your Favour
- [x] Postar resultado prático, se houver. ----- ----- ----- ----- ----- ----- ----- 21/03/2023

Link do MIRO (anotações da aula)
[Anotações da aula EJS no Miro](https://miro.com/app/board/uXjVMeNR-Yw=/)

Repositório da aula no GitHub:
https://github.com/AndreBuitoni/Web-Development/tree/main/todolist-v1

**Comment by AndreBuitoni** [comment]
AULA 266 - Creating your first EJS Template

Nessa aula, achei interessante o uso do SWITCH. Eu não conhecia esse código ainda. Ou, pelo menos, não lembrava dele.
Na imagem abaixo, o início do nosso servidor. Implementando um template usando EJS
![Image](https://user-images.githubusercontent.com/68255266/226640441-8b1cbfad-cb3e-4063-a5fb-eca86403ae26.png)

No HTML, a sintaxe do EJS é feita com <%= insiraSuaVariavelAqui %>
![Image](https://user-images.githubusercontent.com/68255266/226644177-4c424e12-fd11-458b-8a22-bf35bf413e4b.png)

**Comment by AndreBuitoni** [comment]
Aula 269 - The Concept of Scope in the context of Javascript

Utilizamos um formulário simples com um input e um botão submit para enviar dados via POST REQUEST para o servidor.
![Image](https://user-images.githubusercontent.com/68255266/226711110-9d97418c-c487-4382-a06c-c6b84fae6abe.png)

O servidor então recebe os dados inseridos no input, adiciona esses dados num array global com o método push e então redireciona o usuário novamente para o diretório raiz "/" onde agora será renderizado o array atualizado de itens da lista.
![Image](https://user-images.githubusercontent.com/68255266/226711487-b3ff2567-0cba-4e4b-a54e-459ee2b49d3b.png)

Variável itens
![Image](https://user-images.githubusercontent.com/68255266/226711621-fcad204c-0ec6-45f5-b20b-6e1054eb47f6.png)


Renderização da Lista no app.get("/")
![Image](https://user-images.githubusercontent.com/68255266/226711941-065ebb8f-0507-463d-bc1f-d2e1b0fe7cc1.png)

Resultado Prático
![Image](https://user-images.githubusercontent.com/68255266/226712409-7012c554-32ff-45ba-b757-b91a4cb5ec4c.png)

**Comment by AndreBuitoni** [comment]
Aula 269 - The Concept of Scope in the context of Javascript

Aula teórica explicando o conceito de escopo dentro de Javascript e abordando um pouco sobre as diferenças entre var, let e const. Recomendou usar let ao invés de var sempre que possível. Trocou todos os var por let no código.

**Comment by AndreBuitoni** [comment]
Aula 270 - Adding Pre-made CSS Stylesheets to your website

Adicionamos um CSS já pronto para o projeto e então adicionamos as classes e as divs necessárias para utilizar o CSS. Poucas novidades aqui.

O mais interessante foi aprender a autorizar o express a usar arquivos estáticos dentro da pasta public com o seguinte código:
app.use(express.static("public"))

![Image](https://user-images.githubusercontent.com/68255266/226750459-83abac54-751b-49a5-abda-39e9aee7b6eb.png)

Arquivo CSS
https://github.com/AndreBuitoni/Web-Development/blob/main/todolist-v1/public/css/styles.css

**Comment by AndreBuitoni** [comment]
Aula 272 - Understanding node module exports: How to pass functions and data between files

Criamos nosso próprio módulo para melhor entender o que são os módulos do Node.
![Image](https://user-images.githubusercontent.com/68255266/226764663-942cd632-ccf1-4126-aec5-32e6ccb90b2c.png)

Depois, fizemos a requisição desse módulo no servidor:
![Image](https://user-images.githubusercontent.com/68255266/226764756-bb2501bd-499d-4b80-ac12-06c0fba79d0a.png)

Por fim, nos livramos do código extra que estava dentro do app.get("/") (e que agora está no módulo date.js) e simplesmente chamamos o método necessário do nosso módulo com uma linha:
![Image](https://user-images.githubusercontent.com/68255266/226764976-e75e9f6d-6c66-42f0-aa60-2e5fd19fd3a9.png)

Essa aula conclui o capítulo sobre EJS.

**Comment by piantino** [comment]
Massa André, aprendeu bastante coisa que pode ser utilizado no backend em NodeJs e conceitos como formulários e templates que são utilizados em vários frameworks e linguagens diferentes.
