### ISSUE TITLE
Melhorar LinkedIn

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#149]
Melhorar LinkedIn segundo critérios conversados na #129 

- [x] Trocar Full-stack para Front-end no about
- [x] Adicionar curso atual no about 
- [x] Conseguir badges das atividades #63  e #119 
- [x] Pesquisar empresas e recrutadores para melhorar conexões  
- [x] Alterar read me do portifólio no GitHub

Criação da atividade => 37 conexões. 
Atualmente => 92 conexões.

Procurar em empresas de TI:

- https://scinova.com.br/sc-tem-12-empresas-na-lista-das-melhores-de-ti-para-trabalhar-no-brasil/
- https://www.acate.com.br/vagas/
- https://www.acate.com.br/associados/
- https://celta.certi.org.br/graduadas/

**Comment by piantino** [comment]
Ivan tenta filtrar por recrutadores dessa maneira e na próxima semana no avaliamos de novo:

https://www.linkedin.com/search/results/people/?geoUrn=%5B%22106636575%22%5D&industry=%5B%2296%22%2C%224%22%5D&keywords=%23recrutamento&origin=FACETED_SEARCH&profileLanguage=%5B%22pt%22%5D&sid=UuF

**Comment by piantino** [comment]
Lembrete, fazer uma postagem ao mês pelo menos.
