### ISSUE TITLE
Fazer curso "Desenvolvimento Web 2022"

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#15]
114h 43m de conteúdo

**Comment by isabelahyeda** [comment]
https://www.udemy.com/course/web-completo/


- [ ] 1) HTML5
- [ ] 2) CSS3
- [ ] 3) CSS3 Intermediário & avançado
- [ ] 4) HTML5 e CSS3 - Recursos especiais
- [ ] 5) Bootstrap 4 & Design responsivo
- [ ] 6) JavaScript
- [ ] 7) JavaScript Moderno (ECMAScript 2015 - ES6) e Orientação a Objetos
- [ ] 8) PHP 7
- [ ] 9) PHP 7 e Orientação a Objetos
- [ ] 10) Banco de dados MySQL
- [ ] 11) Ajax
- [ ] 12) PHP com PDO
- [ ] 13) Publicação de aplicações Web na Internet
- [ ] 14) JQuery
- [ ] 15) Padrão de arquitetura MVC com PHP
- [ ] 16) PHP 7 & MySQL - Projeto aplicado Twitter Clone
- [ ] 17) API com Slim Framework
- [ ] 18) Introdução ao WordPress (criação de blogs)
- [ ] 19) SASS
- [ ] 20) Criando aplicações Mobile com IONIC
