### ISSUE TITLE
Fazer Seção 23 do curso WebDev Udemy (Angela Yu)

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#150]
Section 23 - Boss Level Challenge 3 - Blog Website

- [x] 274 - A New Challange Format and What We'll Make: A Blog ----- ----- ----- ----- 29/03/2023
- [x] 275 - Setting Up The Blog Project
- [x] 276 - Challenge 1
- [x] 277 - Challenge 1 Solution
- [x] 278 - Challenge 2
- [x] 279 - Challenge 2 Solution
- [x] 280 - Challenge 3
- [x] 281 - Challenge 3 Solution
- [x] 282 - Challenge 4 ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- 30/03/2023
- [x] 283 - Challenge 4 Solution
- [x] 284 - Challenge 5
- [x] 285 - Challenge 5 Solution
- [x] 286 - Challenge 6
- [x] 287 - Challenge 6 Solution
- [x] 288 - Challenge 7
- [x] 289 - Challenge 7 Solution
- [x] 290 - Challenge 8
- [x] 291 - Challenge 8 Solution
- [x] 292 - Challenge 9 ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- 31/03/2023
- [x] 293 - Challenge 9 Solution
- [x] 294 - Challenge 10
- [x] 295 - Challenge 10 Solution
- [x] 296 - Challenge 11
- [x] 297 - Challenge 11 Solution
- [x] 298 - Challenge 12
- [x] 299 - Challenge 12 Solution
- [x] 300 - Challenge 13
- [x] 301 - Challenge 13 Solution
- [x] 302 - Challenge 14 and Solution
- [x] 303 - Challenge 15
- [x] 304 - Challenge 15 Solution
- [x] 305 - Express Routing Parameters
- [x] 306 - Challenge 16 ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- 05/04/2023
- [x] 307 - Challenge 16 Solution
- [x] 308 - Challenge 17
- [x] 309 - Challenge 17 Solution
- [x] 310 - Challenge 18
- [x] 311 - Challenge 18 Solution
- [x] 312 - Challenge 19
- [x] 313 - Challenge 19 Solution
- [x] 314 - Challenge 20  ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- 23/06/2023
- [x] 315 - Challenge 20 Solution
- [x] 316 - Challenge 21
- [x] 317 - Challenge 21 Solution
- [x] 318 - Tip From Angela - When Life Gives You Lemons
- [x] Postar Resultado Prático, se houver.

**Comment by AndreBuitoni** [comment]
AULA 274 -  A New Challange Format and What We'll Make: A Blog

Mostrou o site que vamos criar: um site minimalista estilo blog.

Página 1 - Home:
A página inicial (Home) mostra uma curta introdução e depois uma sequência de todas as entradas que foram feitas no blog. Essas entradas ficam limitadas a 100 caracteres cada uma e um link de "leia mais" fica disponível para  usuário ler a entrada de blog inteira. 

Página 2 - About Us
Página simple com um título e um parágrafo

Página 3 - Contact Us
Página simples com informações de contato

Página Secreta
Uma página escondida que você pode acessar para criar novas postagens do blog, que irão aparecer na home.

OBSERVAÇÃO
Cada postagem de Blog criará uma nova rota com o título da postagem. Exemplo "meublog.com/posts/nova-postagem-32"

AULA FINALIZADA

**Comment by AndreBuitoni** [comment]
Aulas 280 e 281 - Challenge 3

OBJETIVO
Utilizar o conteúdo de header.js e footer.js dentro da página Home.js

EXECUÇÃO
![Image](https://user-images.githubusercontent.com/68255266/228639559-7a83676e-bf05-4b7b-abd4-f1ebf062407a.png)

RESULTADO
![Image](https://user-images.githubusercontent.com/68255266/228639012-fda34c5d-4a6e-4381-9c43-73936fbe8180.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 282 e 283 - Challenge 4

No início da aula, nós modificamos a localização dos arquivos Header.js e Footer.js. Para isso, criamos uma nova pasta (chamada partials) dentro da pasta "views". Com isso, esses componentes deixaram de serem carregados na página Home, pois o EJS somente busca arquivos para incluir que estejam na pasta VIEWS.
![Image](https://user-images.githubusercontent.com/68255266/228994691-a5b47539-9afc-4c00-bb14-a0b7c3111611.png)
![Image](https://user-images.githubusercontent.com/68255266/228994744-1ec3a89c-6b8f-4da3-a2c1-44c6e16ecc3e.png)

O desafio agora é fazer as páginas aparecerem novamente na Home.

**Comment by AndreBuitoni** [comment]
AULAS 286 e 287 - Challenge 6

O desafio agora foi fazer os três botões funcionarem (HOME, ABOUT US, CONTACT US)

A solução ir até o arquivo do header e escrever o caminho que deveria ser requisitado ao servidor "/", "/about" e "/contact"
![Image](https://user-images.githubusercontent.com/68255266/228999697-a5b13609-f324-4feb-aa26-effc33b96e2b.png)

Que moleza hein.

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 288 e 289 - Challenge 7

O desafio consistiu em criar uma página com o caminho '/compose' que tivesse o seguinte layout:
![Image](https://user-images.githubusercontent.com/68255266/229000863-20cabba7-a511-4c1b-9db7-ebcdeb7f4da5.png)

SOLUÇÃO PASSO 1
Criar uma página similar a todas as outras, porém ao invés do parágrafo com "lorem ipsum" adicionei dois elementos HTML, sendo um input do tipo texto e um botão do tipo publish.
![Image](https://user-images.githubusercontent.com/68255266/229001106-019fdb89-faac-46cc-9a8b-73730aab8892.png)

SOLUÇÃO PASSO 2
Agora, criei a rota para essa página no servidor.
![Image](https://user-images.githubusercontent.com/68255266/229001177-5729ec14-7b34-4e32-ac80-973108e0d284.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 289 e 290 - Challenge 8

O desafio foi fazer com que, após o usuário inserir um texto no input da página COMPOSE e clicar no botão PUBLISH, esse texto deveria aparecer escrito no nosso terminal (console.log)

SOLUÇÃO PASSO 1 - O Formulário
Dentro da página compose.ejs -> Envelopamos os componentes INPUT e BUTTON da página COMPOSE em um formulário do tipo POST com a "action" sendo "/compose". Nomeamos o input para "newPost"
![Image](https://user-images.githubusercontent.com/68255266/229005571-d08163ef-8829-438b-8f95-7265487dcb68.png)

SOLUÇÃO PASSO 2 - A Rota POST no Servidor
No servidor (app.js) -> Criação de uma rota post. Criação de uma variável que recebe o texto inserido pelo usuário no INPUT (aqui utilizamos o NOME do input). Por fim, imprimimos no terminal a variável com o console.log
![Image](https://user-images.githubusercontent.com/68255266/229005979-faac8e73-3f99-4a86-801d-7e537d961156.png)


AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 292 e 293 - Challenge 9

O desafio foi remodelar a página, usando bootstrap e HTML, para que ficasse assim:
![Image](https://user-images.githubusercontent.com/68255266/229015225-69f9456b-3a50-4b37-84b6-3d5ff0838d5c.png)

SOLUÇÃO PASSO ÚNICO
A solução foi olhar o site do bootstrap, na área de formulários, para ver algumas classes que poderíamos usar. Resolvi utilizando as seguintes classes e elementos:
![Image](https://user-images.githubusercontent.com/68255266/229015550-6997999b-3155-4dfb-add7-7f8a2a253a04.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 294 e 295 - Challenge 10

O desafio era guardar as informações que o usuário insere na página COMPOSE dentro de um objeto localizado dentro do servidor no método POST "/compose".

SOLUÇÃO PASSO ÚNICO
Criamos o objeto da seguinte forma:
![Image](https://user-images.githubusercontent.com/68255266/229017854-1d7efded-2bb9-4a2e-8a1f-de4c50d9204b.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 296 e 297 - Challenge 11

Neste desafio foi solicitado o seguinte:
1- Criar uma variável global no servidor do tipo array, sem nenhum valor atribuido.
2- Dentro da rota POST "/compose" devemos acessar e modificar essa variável global para incluir o objeto post (que contém o título e corpo da postagem do usuário)
3- Ainda na mesma rota, após o passo anterior direcionar o usuário para a página HOME.
4- Na página home, adicionar um console.log para imprimir a variável global criada no passo 1.

SOLUÇÃO PASSO 1 - Variável Global
Criei a variável no servidor antes das rotas.
![Image](https://user-images.githubusercontent.com/68255266/229023167-a9bd4081-8f51-4aa9-88dc-75e1944280a9.png)

SOLUÇÃO PASSO 2 e 3 - Alterações no app.post('/compose")
![Image](https://user-images.githubusercontent.com/68255266/229023381-0b593026-7099-425d-b9d4-169efcaff766.png)

SOLUÇÃO PASSO 4 - Alteração no app.get("/")
![Image](https://user-images.githubusercontent.com/68255266/229023545-37d54838-b7c6-49a2-b987-0cd92e2d31b6.png)

RESULTADO - Após fazer dois novos posts na página compose, fui redirecionado duas vezes para a página HOME e no terminal é impressa a variável _posts_ que acumula todas as postagens feitas, conforme abaixo.
![Image](https://user-images.githubusercontent.com/68255266/229023904-b0842b01-4934-4e48-a197-4eb179a372d7.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
Aulas 298 e 299 - Challenge 12

O desafio foi remover o console.log que estava no servidor e passá-lo para a página HOME. 

SOLUÇÃO PASSO 1 - Passando o Array do servidor para a página Home
Primeiro, adicionei mais um par key:value dentro do objeto que está sendo passado pelo método GET. Nesse par eu passo o valor do array contendo os posts.
![Image](https://user-images.githubusercontent.com/68255266/229174325-7db1381c-9add-4368-b343-72d92aa71561.png)

SOLUÇÃO PASSO 2 - Imprimindo o console.log pela página Home
Depois, inseri o console.log na HOME fazendo uso das TAGS EJS adequadas para execução de JavaScript.
![Image](https://user-images.githubusercontent.com/68255266/229174577-a501e8c5-d64d-4c67-a30f-f2e2c82d559f.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 300 e 301 - Challenge 13

DESAFIO
Mudar o código para que o console.log mostre somente o TÍTULO das entradas no blog, de maneira que conforme o usuário adicione mais entradas no blog, o console.log imprima todos os títulos já usados anteriormente.

SOLUÇÃO
Criei um loop FOR que é executado a cada vez que a página HOME é carregada. Esse loop passa por todos os valores do array contendo as entradas do blog e imprime selecionando do objeto somente o valor correspondente aos títulos.
![Image](https://user-images.githubusercontent.com/68255266/229194114-7eebb9d4-2a80-4de4-b9bd-3c1b77d6cfb9.png)

RESULTADO NO TERMINAL - Após o usuário inserir três entradas no blog, e cada entrada direcionar para a página home.
![Image](https://user-images.githubusercontent.com/68255266/229194467-8b174fdb-c929-4682-bc12-6088590dff8a.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 303 e 304 - Challenge 15

DESAFIO
Agora chegou o momento de retirar o console.log e, ao invés disso, renderizar os TÍTULOS e os CORPOS das entradas de blog diretamente no website.

SOLUÇÃO
Modifiquei o loop forEach() de maneira que agora, a cada ciclo ele cria novos elementos HTML ( h1 e p ) contendo dentro deles a valor das variáves que estavam segurando o conteúdo das entradas de blog. Para isso, modifiquei as TAGS EJS para as tags que imprimem o valor das variáves ( antes era essa <% variavelAqui %> agora é essa <%= variavelAqui %> )
![Image](https://user-images.githubusercontent.com/68255266/229203960-1a94fec7-f962-448f-9acc-593e02fe4a5a.png)

RESULTADO
![Image](https://user-images.githubusercontent.com/68255266/229204061-0406179d-ea9f-40c8-8ae3-1b67f90e75c5.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULA 305 - Express Routing Parameters

Curta aula teórica explicando sobre como o express possibilita criar rotas usando parâmetros
![Image](https://user-images.githubusercontent.com/68255266/229206714-afaf3f6e-a43e-4b5b-921e-8429058c8e87.png)
![Image](https://user-images.githubusercontent.com/68255266/229206646-f5040933-8440-414d-86cb-029dbe461db2.png)

AULA FINALIZADA

**Comment by AndreBuitoni** [comment]
AULAS 308 e 309 _ Challenge 17

DESAFIO
Criar uma entrada no blog com o título "Test". Após isso, ao colocar essa palavra na URL (/posts/Test) o terminal deverá mostrar "Match Found!"

SOLUÇÃO
No servidor, criamos um IF para detectar se o :postName é igual a "Test"
![Image](https://user-images.githubusercontent.com/68255266/230150320-cc15c398-2e93-4055-b90d-34b13e032f0d.png)

RESULTADO
Criamos uma entrada com título "Test" e adicionamos esse título na URL.
![Image](https://user-images.githubusercontent.com/68255266/230149724-79fa7799-3e9f-4491-91e0-732ad9331983.png)
No terminal, detectamos a igualdade
![Image](https://user-images.githubusercontent.com/68255266/230150026-b1822ac1-135a-476b-ad17-d43c46f32062.png)


AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 310  e 311 - Challenge 18

DESAFIO
A instrutora Angela Yu nos introduziu para a biblioteca "lodash". Essa biblioteca contém um método chamado ".lowerCase" que transforma caracteres em strings para umm formato padrão em minúsculas. O desafio era instalar e requisitar essa biblioteca no servidor para depois fazer com que uma entrada com título "Another post" resultasse em um match com a busca na URL /posts/another-post

SOLUÇÃO
Instalamos a biblioteca lodash via npm com "npm i lodash". Depois requisitamos ela:
![Image](https://user-images.githubusercontent.com/68255266/230159930-64da2ea0-8770-489d-b1e6-aaa13c8d2591.png)

Depois, utilizamos o método _.lowerCase nas duas variáveis sendo comparadas pelo nosso loop forEach
![Image](https://user-images.githubusercontent.com/68255266/230160245-1df0b517-ed11-4a24-a97e-f0184e4c2a5b.png)

RESULTADO
![Image](https://user-images.githubusercontent.com/68255266/230160464-225c71c4-23e8-4aae-a008-273003d3b403.png)
![Image](https://user-images.githubusercontent.com/68255266/230160542-24ec10bf-05c6-4171-9475-9d3db140b005.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 312 e 313 - Challenge 19

DESAFIO
Agora, quando o usuário digitar na URL o nome de uma entrada de blog ( exemplo: /posts/parque-beto-carrero ), uma nova página deverá ser renderizada mostrando o conteúdo dessa entrada (título e corpo do texto).

SOLUÇÃO PASSO 1 - Criação do Template "post.ejs"
![Image](https://user-images.githubusercontent.com/68255266/230177312-b47c2739-7cb1-4b79-bfe5-7e22851c6ced.png)

SOLUÇÃO PASSO 2 - Alteração da rota '/posts/:postName'
![Image](https://user-images.githubusercontent.com/68255266/230177567-290f9162-80b3-4fd5-a680-ee936356f5d1.png)

RESULTADO
Na página Home, as entradas do blog:
![Image](https://user-images.githubusercontent.com/68255266/230178145-4da1e0ed-0554-457f-97a4-2959784f633d.png)

Quando o URL é igual ao título do blog:
![Image](https://user-images.githubusercontent.com/68255266/230178509-77c6efeb-dc90-4c64-b8dd-f92e4fc8b029.png)

AULAS FINALIZADAS

**Comment by AndreBuitoni** [comment]
AULAS 314  e 315

DESAFIO
Limitar os caracteres das postagens de blog que aparecem na página Home para 100 caracteres e adicionar reticências no final do texto.

SOLUÇÃO - Adicionar o método substring para o texto sendo postado:
![Image](https://github.com/saibrotech/mentoria/assets/68255266/8ccdca1c-012d-4a5a-bc72-4a7b485b8f34)

RESULTADO - Texto aparece cortado no homepage
![Image](https://github.com/saibrotech/mentoria/assets/68255266/2129feeb-a8a8-4e0f-b245-2459d14efca1)

Aulas Finalizadas

**Comment by AndreBuitoni** [comment]
Aulas 316 e 317

DESAFIO
Adicionar, no final de cada postagem na Homepage, uma string "Read More" que é um link. Ao ser clicado o link deve abrir a página específica daquela postagem de blog, que conterá o conteúdo do post na íntegra.

SOLUÇÃO
No mesmo parágrafo onde foi adicionado o método substring, adicionar a tag âncora para o post em questão:
![Image](https://github.com/saibrotech/mentoria/assets/68255266/a3bdb507-f0dd-4868-a706-20f814f270a3)

RESULTADO
![Image](https://github.com/saibrotech/mentoria/assets/68255266/6aa16d77-dc54-47d5-aff5-f8472ee7669e)
![Image](https://github.com/saibrotech/mentoria/assets/68255266/2fc1df71-1a19-469a-8b9a-c33eec27fec8)

Aulas Finalizadas

**Comment by AndreBuitoni** [comment]
Com isso, concluo a seção 23 do curso.

**Comment by piantino** [comment]
Revisado, parabéns!
