### ISSUE TITLE
Avaliar cursos Javascript

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#151]
https://portogente.com.br/noticias-corporativas/115352-melhor-curso-javascript

**Comment by piantino** [comment]
Opção do básico ao intermediário:
https://www.udemy.com/course/curso-web/

**Comment by PaulaBuitoni** [comment]
Optei por esse aqui..

Curso de JavaScript e TypeScript do básico ao avançado
Javascript e TypeScript - front-end e back-end (Full Stack) - Node, Express, noSQL, React, hooks, Redux, Design Patterns

https://www.udemy.com/course/curso-de-javascript-moderno-do-basico-ao-avancado/#reviews

Pois esse anterior, eu vi nos comentário que parece estar bem desatualizado e o professor não da retorno. 

Deixei esse salva, porém vou efetuar a compra em si, só quando eu terminar o do Guanabara, uma vez que o peço parece não mudar nunca.

**Comment by piantino** [comment]
Sugiro que faça o mesmo curso que o André vai fazer por ser mais prático:
https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/
