### ISSUE TITLE
Criar planilha de vagas

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#154]
Exemplo da Nicole:
https://docs.google.com/spreadsheets/d/1TSdSuR8eM6cf1Cky2csmk6wfxb-IE2BYusutcOT5MGo/edit#gid=0

**Comment by nilljr** [comment]
https://docs.google.com/spreadsheets/d/1gov1IlZ_1KA0BnRm4NIakfS9WQO0Bc7wf8wa6DwqATk/edit?pli=1#gid=0
