### ISSUE TITLE
CURSO: React.js e Next.js - Seção 1 Introdução

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#163]
Seção 1 - Introdução

- [x] 1. Introdução                 ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- 28/07/2023
- [x] 2. Conheça este curso e como os tópicos serão abordados  ----- ----- ----- ----- 28/07/2023
- [x] 3. Tirando melhor proveito das perguntas e respostas dos cursos  ----- ----- ----- ----- 28/07/2023

**Comment by AndreBuitoni** [comment]
Esta seção toda foi bem introdutória mesmo. 

- Vi como o curso está estruturado;
- Aprendi como podemos utilizar a ferramenta da perguntas da Udemy para tirar dúvidas com o professor;
- Obtive acesso ao discord do curso (apenas para dúvidas entre colegas)

Seção finalizada.

**Comment by piantino** [comment]
Muito bom!
