### ISSUE TITLE
Avaliar o Linkedin do Juninho e levantar pontos de melhoria para todos

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#166]
### Referências

https://www.linkedin.com/in/gutivalente/
https://www.linkedin.com/in/naniavalone/
https://www.linkedin.com/in/ivan-carlos-duarte-junior/

Pontos: 

- [x] Adicionar páginas português/inglês
- [x] Detalhar experiências e estudos
- Realizar testes de badge https://github.com/saibrotech/mentoria/issues/179, https://github.com/saibrotech/mentoria/issues/177, https://github.com/saibrotech/mentoria/issues/178
- [x] Inserir links na aba de contato
- [x] Inserir mais informações na aba Sobre
- [x] Adicionar features
- [x] Adicionar idiomas em uma aba separada
- [x] Destacar conhecimentos em hardware
- [x] Adicionar projetos em andamento e projetos do curso
- [x] Adicionar experiência de ONG
- [ ] Trocar foto

**Comment by piantino** [comment]
LinkedIn antes:

[Nill Junior _ LinkedIn-antes.pdf](https://github.com/saibrotech/mentoria/files/12517308/Nill.Junior._.LinkedIn-antes.pdf)

**Comment by piantino** [comment]
Como conversamos, criar atividades separadas para tentar badges do LikedIn.

**Comment by piantino** [comment]
Sugestão:

- Trocar capa de fundo
- Ordenar na descrição, colocando as linguagens antes.
- Ordenar as skills:


![Image](https://github.com/saibrotech/mentoria/assets/737364/ccfd97ef-1fe2-4eed-ac56-b5ccade85bff)

**Comment by nilljr** [comment]
![Image](https://github.com/saibrotech/mentoria/assets/89917303/c8c1e62f-8410-4a85-a124-d80be43d73dd)

![Image](https://github.com/saibrotech/mentoria/assets/89917303/bd882e43-121a-454e-b93e-597be900291b)

![Image](https://github.com/saibrotech/mentoria/assets/89917303/783fdb9c-2a29-4fbd-9d25-8d539387736f)
