### ISSUE TITLE
Fazer Codelabs do Google - Introdução ao Angular

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#167]
Descrição
Este é um minicurso (codelabs) disponibilizado pelo Google para introduzir a programação com Angular. O vídeo do curso é em inglês, mas o passo-a-passo está disponível em português também.

Link do Minicurso
https://codelabs.developers.google.com/introduction-to-angular?hl=pt-br

Link do vídeo tutorial
https://www.youtube.com/watch?v=qxchrt04bTA

Partes da Tarefa

- [x] Realizar todos os 9 passos do codelabs para aprender o básico de Angular
- [x] Postar resultado prático, se houver

**Comment by AndreBuitoni** [comment]
Terminei esse pequeno curso de introdução ao ANGULAR. O resultado foi um início de um site de buscas de apartamentos que apresenta ao usuário uma foto do local, e dados sobre o imóvel (se possui lavandaria e wifi).
![Image](https://github.com/saibrotech/mentoria/assets/68255266/10cf31a5-c0e7-47b6-8dda-35704c794218)

Na estrutura de arquivos, tivemos apenos o componente principal (app.component) e um componente de listagem de casas (housing-list.component)
![Image](https://github.com/saibrotech/mentoria/assets/68255266/d6096c5e-7ae8-42ef-be04-3063ec14369b)

**Comment by AndreBuitoni** [comment]
Achei o projeto muito interessante. Consegui concluir em poucas horas e tive uma introdução motivadora para trabalhar com Angular.

**Comment by piantino** [comment]
Boa iniciativa em buscar e fazer esse curso.
