### ISSUE TITLE
Estudos Iniciais sobre TypeScript e Angular

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#168]
Estou buscando mais um pouco mais Angular
Link: https://www.youtube.com/watch?v=k5E2AVpwsko

- [x] Conceitos Básicos em TypeScript ---- ---- ---- ---- ---- 15/08/2023
- [x] Conceitos Básicos em Angular ---- ---- ---- ---- ---- 15/08/2023

TYPESCRYPT - Conceitos Básicos
![Image](https://github.com/saibrotech/mentoria/assets/68255266/66639874-b537-4c1c-a5b1-32c8d7437a07)

ANGULAR - Conceitos Básicos
![Image](https://github.com/saibrotech/mentoria/assets/68255266/e7813537-6809-4d0e-83c1-4669cbe05d6f)

**Comment by AndreBuitoni** [comment]
Aulas concluídas.

**Comment by piantino** [comment]
Se tiver alguma dúvida coloca no Discord.
