### ISSUE TITLE
Fazer Tech Talk sobre Desenvolvimento mobile com React Native

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#169]
- React native
- Expo
- Caso prático de utilização

LINK PARA A APRESENTAÇÃO
https://docs.google.com/presentation/d/1-BPwy62nZ0-8tFIrSrJQmWsdvxT8avrdYFnY77z8AvE/edit#slide=id.p

**Comment by AndreBuitoni** [comment]
Perfeito, estou começando a montar a apresentação.

**Comment by piantino** [comment]
Normalmente a gente colocava as apresentações aqui:
https://drive.google.com/drive/folders/1ESmdOXKBaVY16Qucd9E2jsUjbCYGfozD
