### ISSUE TITLE
NLW  IA (Next Level Week)  -Trilha Foundations) -  Rocketseat

### ISSUE THREAD

**Issue by PaulaBuitoni** [saibrotech/mentoria#172]
Na trilha Foundations vamos inserir a inteligência artificial dentro do nosso projeto com dois modelos de IA: um para extrair texto do áudio e outro para resumir o conteúdo.

- [x]   Live abertura  - Introdução 
- [x]   Aula 01 - Primeiros passos: iniciando o projeto
- [x]   Aula 02 - Avançando em programação: é hora do back-end
- [x]   Aula 03 - Últimos ajustes: inserindo a IA no código
- [x]   Encerramento oficial (e próximos passos com IA)
- [x]   Quiz para emitir certificação
- [x]   Emitir certificado

**Comment by PaulaBuitoni** [comment]
Curso concluído com sucesso.

Certificado postado no linkedin : https://app.rocketseat.com.br/certificates/44e6893d-5338-4385-8f5b-f7ad7c22fab6

Link da aplicação no Github : https://github.com/PaulaBuitoni/NLW-IA

![Image](https://github.com/saibrotech/mentoria/assets/68255632/265bee8f-dbf8-47f4-8157-99b2300e5225)
![Image](https://github.com/saibrotech/mentoria/assets/68255632/5dde22fe-a5d9-4fca-a465-eb0e74899e3a)
![Image](https://github.com/saibrotech/mentoria/assets/68255632/5fe58748-842b-44a7-9037-306a2dcb95e0)

................. Gostei no curso, e baixei os vídeos das aulas. Acredito que posso voltar e rever  para construir algo semelhante porém melhorado.

**Comment by piantino** [comment]
Muito bom Paulinha, acho que esse tipo de projeto tem tudo a ver com você, já que junta programação e youtube.
