### ISSUE TITLE
Atualizar Linkedin

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#175]
Atualizações Realizadas

- [x] Seção About (sobre mim) ---> Mais informações e chamadas para serviços freelancers
- [x] Seção Projetos ---> Projeto Drinkifyme adicionado (copiado do Juninho)
- [x] Seção Serviços ---> Novos serviços adicionados
- [x] Alterações no banner ---> Novas ferramentas favoritas, lettering alterado, mudanças sutis no design
- [x] Seção ABOUT em inglês também foi atualizada

Acesse em
https://www.linkedin.com/in/andre-buitoni/

**Comment by AndreBuitoni** [comment]
ABOUT VERSÃO "LANDINGPAGE"
![Image](https://github.com/saibrotech/mentoria/assets/68255266/f4c139c2-baa4-4188-88dd-41aa19d28e8c)

ABOUT "MAIS INFORMAÇÕES"
![Image](https://github.com/saibrotech/mentoria/assets/68255266/9b039787-ce3f-4668-9e01-7fab6573b696)
![Image](https://github.com/saibrotech/mentoria/assets/68255266/352d6590-6b60-458d-b25a-b245af3e0b88)

**Comment by AndreBuitoni** [comment]
SEÇÃO SERVIÇOS
--> Essa seção possui limite de 500 caracteres, por isso não detalhei serviços de programação. Acho mais difícil procurarem por freelancer de programação pelo linkedin, então deixei de edição de vídeo e outros.
![Image](https://github.com/saibrotech/mentoria/assets/68255266/41f5af1f-4ec0-47a5-bd47-4b940003c644)

**Comment by AndreBuitoni** [comment]
IMAGEM DO BANNER
---> Novas Ferramentas, novo lettering, alterações sutis no design
![Image](https://github.com/saibrotech/mentoria/assets/68255266/7888c55d-7cd0-414f-8077-966655d2b148)

**Comment by piantino** [comment]
@AndreBuitoni o seu perfil está bem completo, principalmente ter em inglês e português.

Agora é ir mantendo as postagens e evoluir alguns pontos:

1. Tentar outras Badges: CSS, Javascript, React
2. Aumentar o número de conexões relevantes, sugiro procurar por recrutadores específico de IT, e de profissionais de TI de empresas da região. Participar de eventos ajuda.
