### ISSUE TITLE
Fazer curso Suporte em TI do Google

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#20]
Curso Fundamentos do Suporte Técnico.
Início: 29/08/2022
Término: 09/12/2022

https://www.coursera.org/programs/2022-2-sc-turma-1-noite-ra2t3?collectionId=D4f4R&currentTab=CATALOG&productId=QE4tKYGmEem2fgrSf7QW9A&productType=s12n&showMiniModal=true

- [x] INTRODUÇÃO A TI
- [x] Hardware
- [x] Sistema operacional
- [x] Redes
- [x] Software
- [x] Resolução de problemas

Curso Estrutura e Funcionamento das Redes de Computadores

- [x] Introdução a redes
- [x] A camada de rede
- [x] As camadas de transporte e aplicação
- [x] Serviços de redes
- [x] Conexão com a Internet
- [x] Solução de problemas e o futuro das redes

Curso Sistemas Operacionais e Você: Tornando-se um Usuário Avançado

- [x] Navegando no sistema
- [x] Usuários e permissões
- [x] Gerenciamento de pacotes e softwares
- [x] Sistemas de arquivo
- [x] Gerenciamento de processos
- [x] Sistemas operacionais na prática

Curso Administração de Sistemas e Serviços de Infraestrutura de TI

- [x] O que é administração de sistema?
- [x] Serviços de rede e infraestrutura
- [x] Serviços de plataforma e software
- [x] Serviços de diretório
- [x] Recuperação de dados e backups
- [x] Projeto final

Curso Segurança de TI: Defesa Contra as Artes Obscuras do Mundo Digital

- [x] Entendendo as ameaças à segurança
- [x] Pelcgbybtl (criptologia)
- [x] Segurança com AAA
- [x] Protegendo redes
- [x] Defesa profunda
- [x] Criando uma cultura de segurança na empresa

Formatura

- [x] Participar da formatura ( 15/12 )
- [x] Receber certificado

**Comment by piantino** [comment]
Postagem:

https://www.linkedin.com/posts/ivan-carlos-duarte-junior_certificado-profissional-de-suporte-em-ti-activity-7016883097937809408-8Hrm
