### ISSUE TITLE
Hands On: Currículo - Melhorando meu LinkedIn - Parte 2

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#29]
Continuação da primeira parte: #26 

- [x] Alinhar cargos e funções no LinkedIn
- [x] Adicionar "Talks About"
- [x] Adicionar links no certificado (pode ser último certificado)
- [x] About - Colocar o que estão fazendo no momento com palavras chaves.
- [x] Editar/Adicionar experiência na Saibrotech e adicionar skill
- [x] Atualizar certificados
- [x] Atualizar linguagem, pelo menos inglês básico
- [x] Aprimorar skills e reconhecer de colegas
- [x] Adicionar trabalho voluntário dos novos caminhos (Gustavo, André e Nani)
- [x] Adicionar trabalho voluntário dos mentores na Saibrotech (André, Nicole, Gustavo e Freddy)
- [x] Atualizar interesses, seguindo empresas
- [x] Atualizar o sobre com os links do portfólio
- [x] Fazer testes do LinkedIn para ganhar o badge

**Comment by Nibuitoni** [comment]
Nani - ajustar cargo para analista de dados na Saibrotech, colocar o about em português quando a página estiver em português, adicionar voluntariado no Projeto novos caminhos
Isa - adicionar tags, link de certificado no featured, melhorar o about adicionando skills e experiências, adicionar mais certificados.
Ivan - adicionar tags e link de certificado no featured, pode adicionar no about que está hazendo o cruso de suporte no JA. 
André Piantino - adicionar voluntariado no Projeto novos caminhos e na Saibrotech
Fred e Gustavo - Adicionar trabalho voluntário da Saibrotech
Nicole - adicionar tags, link de certificado no featured, adicionar trabalho voluntário da Saibrotech, certificados

Todos - reconhecer skill dos colegas
