### ISSUE TITLE
Tentar Badge HTML no LinkedIn

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#30]
- [x] Estudar material de estudo
- [x] Isabela fazer teste
- [x] Ivan fazer teste

## Material de estudo
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes

**Comment by piantino** [comment]
@isabelahyeda o badge de HTML não aparece na skill.

**Comment by piantino** [comment]
@IvanCarlosJr tentar novamente em Abril de 2023 #63

**Comment by isabelahyeda** [comment]
![Image](https://user-images.githubusercontent.com/98404083/195150123-cbf3800f-52ce-46fa-9919-fe5231c06c15.png)
