### ISSUE TITLE
Hands On: Criar meu portfólio

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#34]
### Criar seu repositório pessoal

- [x] Andre - https://github.com/piantino/piantino
- [x] Ivan - https://github.com/IvanCarlosJr/IvanCarlosJr

### Criar projeto Next.js

Simplesmente criar o projeto Node e adicionar as dependências básicas.

https://nextjs.org/docs/getting-started

- [x] Andre - https://github.com/piantino/piantino
- [x] Ivan - https://github.com/IvanCarlosJr/IvanCarlosJr

### Escolher o Design da página

Procurar no figma, sites de templates, por um layout que deseja.

https://bootstrapmade.com/bootstrap-portfolio-templates/

- [x] Andre - https://bootstrapmade.com/demo/iPortfolio/
- [x] Ivan - https://bootstrapmade.com/demo/Personal/

### Definir os itens a serem colocados:

* Stack: Linguagem, bibliotecas, ferramentas
* ...

Etapas:
- [ ] Criar evento no discord
- [ ] Criar html base com bootstrap
- [ ] Adicionar no LinkedIn como Website (destaque)

**Comment by piantino** [comment]
Testar:
https://www.gitshowcase.com

**Comment by nanipumpkin** [comment]
Dei uma de metida e resolvi testar esse link aí... (kkk) Se quiserem dar uma olhada como ficou: [gitshowcase-nani](https://www.gitshowcase.com/nanipumpkin)

**Comment by piantino** [comment]
Estou encerrando essa atividade, mas fica registrado para os novos mentorados @AndreBuitoni , @PaulaBuitoni e @nilljr a dica da Nani e a sugestão de no futuro criar o site de portfólio deles.
