### ISSUE TITLE
Analisar oportunidade T.EX

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#43]
https://jobs.kenoby.com/cogna/job/processo-seletivo-para-bolsas---tex/6319ff842e51051567ecebb7?x-token-internal=c60ee62928fa01db4c12f29f26463fb69c7cc79e271da27a4f7abb9b8e05780a8e762639d85bf960ad75c62bf7d6899ee4854f8171b0884bc2d7122e7260751e&utm_source=internal

**Comment by Freddyminu** [comment]
Link do processo seletivo: https://jobs.kenoby.com/cogna/job/processo-seletivo-para-bolsas---tex/6319ff842e51051567ecebb7?x-token-internal=c60ee62928fa01db4c12f29f26463fb69c7cc79e271da27a4f7abb9b8e05780a8e762639d85bf960ad75c62bf7d6899ee4854f8171b0884bc2d7122e7260751e&utm_source=internal

Chance: Bolsa de Estudo + Chance de ser contratado (100 vagas de formação em Dois Fullstack, Java e JavaScript)
Quem se destacar, tem chance de trabalhar na Cogna.

Para entrar:
 - Passar no processo seletivo ( Português, Matemática, Lógica e Lógica de Programação )
 - Ter 40h semanais livres para aulas ao vivo e gravadas.

**Comment by piantino** [comment]
![Image](https://user-images.githubusercontent.com/737364/192512962-f914bcd0-2da0-48b7-8fe6-4a18c9cc540c.png)
