### ISSUE TITLE
Avaliar como documentar material de estudos para mentorados

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#45]
Eu sugiro a gente criar um compilado de links para materiais interessantes de aprendizado, separado por tema. Talvez a gente podia criar um pacote de vídeos/tutoriais para novos mentorados. Quem sabe depois podemos até agrupar todos esses materiais em uma página web ou app para celular, como forma de praticarmos nossas habilidades. Daí poderíamos sugerir alguns materiais para o mentorado assistir a cada semana. EXEMPLO:
Semana 1:
- Diferença de Front-End / Back-End (vídeo de 5 minutos)
- Basicão Front-End - O que é HTML/CSS/JavaScript (vídeo de 20-30 minutos)
- Basicão Back-End - O que é Python - O que são banco de dados etc (20-30 minutos)
- O que é Figma
etc
etc

Basicamente seria tipo uma biblioteca da SaibroTech. Inicialmente poderíamos hospedar isso no GitHub. O que acham?

-----
A seguir, um mero compilado de links para depois organizarmos.

ESBOÇO (ir construindo aos poucos) - quem quiser pode contribuir com links
IMPORTANTE: Os horários indicados representam apenas o tempo de duração dos conteúdos dos cursos (por exemplo quantas horas de vídeos), mas na prática você irá gastar muito mais tempo em cada curso, pois haverão atividades práticas para serem concluídas.

FIGMA:
[Gabriel Silvestri - Curso de Figma](https://www.youtube.com/watch?v=5rEWrhYRBqw) - Vídeo no YouTube - 1h30 - sem certificado
[DIO - Introdução Prática ao Figma](https://web.dio.me/course/introducao-pratica-ao-figma/learning/30e6a999-5fd9-4e6e-aaf7-c047980ab33e/?back=/home) - Playlist no website da DIO de 5 vídeos - com certificado gratuito

GIT / GITHUB / GITLAB:
[DIO - Introdução ao Git e GitHub](https://web.dio.me/course/introducao-ao-git-e-ao-github/learning/75b9fe49-6ed4-4480-83a7-7e37fc356aa9/?back=/home)
[DIO - Trabalhando com Git e GitLab na prática](https://web.dio.me/course/trabalhando-com-git-e-gitlab-na-pratica/learning/b05c2fe6-9831-445a-a27d-9aa3434a25f8/?back=/home)
[DIO - Git e GitHub focado em Pull Request](https://web.dio.me/course/git-e-github-focado-em-pullrequest/learning/7ee9e586-a200-41de-a075-fd6a7b4b5a1e/?back=/home)
[Guanabara - Git e GitHub](https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA)

BOOTCAMPS WEBDEVELOPER:
[Udemy - Complete Web Development Bootcamp - Dr.Angela Yu](https://www.udemy.com/course/the-complete-web-development-bootcamp/) Curso com várias playlists e atividades - 65h - com certificado pago

HTML e CSS:
[Guanabara HTML e CSS - Módulo 1 - Primeiros Passos HTML e CSS](https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n) - Playlist no YouTube 41 videos - 40h - com certificado pago
[Guanabara HTML e CSS - Módulo 2 - Deixando as Coisas Mais Bonitas](https://www.youtube.com/playlist?list=PLHz_AreHm4dlUpEXkY1AyVLQGcpSgVF8s) -  Playlist no YouTube 43 videos - 40h - com certificado pago
[Guanabara HTML e CSS - Módulo 3 - Colocando um Protótipo no Ar](https://www.youtube.com/playlist?list=PLHz_AreHm4dmcAviDwiGgHbeEJToxbOpZ) -  Playlist no YouTube 40 videos - 40h - com certificado pago
[Guanabara HTML e CSS - Módulo 4 - Aprofundando os Conhecimentos](https://www.youtube.com/playlist?list=PLHz_AreHm4dkcVCk2Bn_fdVQ81Fkrh6WT) - Playlist no YouTube 45 videos - 40h - com certificado pago
Guanabara HTML e CSS - Módulo 5 - Novas Teconologias --- em construção (11/out/2022) - 40h
[Material PDF para as aulas do Guanabara](https://github.com/gustavoguanabara/html-css/tree/master/aulas-pdf) - PDF

JAVASCRIPT:
[Rocketseat - TUDO que você deve estudar de JavaScript antes do React](https://www.youtube.com/watch?v=37SwqREHRGI) - 1h25
[Guanabara - Curso Grátis de JavaScript e ECMAScript para Iniciantes](https://www.youtube.com/watch?v=1-w1RfGIov4&list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1) - Playlist no YouTube 33 videos

OUTRAS FERRAMENTAS / REFERÊNCIAS: (serão organizadas no futuro)
[Conheça o Tangram, o design system da RD Station](https://www.youtube.com/watch?v=IKeTaAn8aRU) - Vídeo do YouTube - 3min
[Website Tangran RD Station](https://tangram.rdstation.com.br/) - website - Design System da RD
[ADELE - The repository of publicly available design systems and pattern libraries](https://adele.uxpin.com/) - website

PLATAFORMAS DE ENSINO INTERESSANTES:
[Rocketseat](https://www.rocketseat.com.br/)
[DIO](https://www.dio.me/)
[FreeCodeCamp](https://www.freecodecamp.org/)
[DataCamp] - tentei pegar o link mas vai direto no meu perfil - corrigir

**Comment by piantino** [comment]
Na parte do figma podemos adicionar o curso #44

**Comment by AndreBuitoni** [comment]
Já comecei a adicionar algumas referências. Aos pouquinhos vamos aprimorando. Quem puder, e quiser contribuir, fiquem à vontade. Abs

**Comment by piantino** [comment]
Material sobre carreiras:
https://www.vagas.com.br/mapa-de-carreiras/

**Comment by piantino** [comment]
@AndreBuitoni devido a minha falta de tempo para organizar essa atividade, acho que seria mais produtivo se você colaborasse com algum projeto já existe, exemplos:

https://github.com/SouJunior/soujunior-lab#02-video4me
https://github.com/arthurspk/guiadevbrasil
https://github.com/arthurspk/guiadofrontend
https://roadmap.sh/roadmaps

O que acha?

**Comment by AndreBuitoni** [comment]
@piantino Agradeço a sugestão, mas minha ideia inicial era criar algo colaborativo para todos os mentorados da SaibroTech irem adicionando links ou PDF's que fossem interessantes para os outros mentorados ou novos que viriam no futuro. Analisando a situação agora, acho que o projeto perdeu o sentido. Eu, sozinho, ir colaborar com outro projeto fora daqui, não me interessa. A ideia era mais criar material para a SaibroTech. Acho que o mais indicado agora é desativar o projeto. Da minha parte também já tenho muitas coisas para fazer.
