### ISSUE TITLE
Concluir trilha Data Analyst no DataCamp

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#46]
Carga horária: 36 h
[Data Analyst with Python](https://app.datacamp.com/learn/career-tracks/data-analyst-with-python?version=8)

- [x] Introduction to Data Science in Python
- [x] Intermediate Python
- [x] Data Manipulation with Pandas
- [x] Joining Data with Pandas
- [x] Introduction to Statistics in Python
- [x] Introduction to Data Visualization with Seaborn
- [x] Data Manipulation with Python
- [x]  Importing & Cleaning Data with Python
- [x] Exploring Data Analysis in Python
- [x] Sampling in Python
- [x] Hypothesis Testing in Python

**Comment by nanipumpkin** [comment]
[data_analyst_python.pdf](https://github.com/saibrotech/mentoria/files/9737990/data_analyst_python.pdf)

**Comment by piantino** [comment]
Parabéns Nani!
Mais um passo importante conquistado.
