### ISSUE TITLE
DataCamp - ETL in Python

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#47]
[ETL in Python](https://app.datacamp.com/learn/courses/etl-in-python)
4 hours |  16 Videos | 48 Exercises | 6,937 Participants | 3,850 XP

**Course Description**
Want to grow your data engineering skills and more efficiently process big data? Well, it’s time to develop your ETL skills. In this course, you’ll learn the foundations of creating pipelines to efficiently extract, transform, and load data into the systems your company commonly uses. You’ll get hands-on experience by helping a fictional private equity firm process the sales data they need to make informed business decisions when buying real estate. Jump in, learn how to create ETL pipelines, and develop one of the most in-demand engineering skills needed in the market.

**1. Explore the data and requirements**
In this first chapter, you’ll be introduced to your role as a data engineer in a private equity fund. You'll be exposed to the whole ETL pipeline before deep-diving into its first phase: the **extraction** process.
- [x] Introduction to ETL in Python
- [x] The ETL process
- [x] Downloading a ZIP file
- [x] Exploring a ZIP file
- [x] Ask the right questions
- [x] Reading from a CSV file
- [x] Writing to CSV
- [x] Extracting
- [x] Downloading the new dataset file from web
- [x] Project folder structure
- [x] Extract 'em all!

**2. Create the ETL foundations**
In this chapter you're going to create some important foundations for our ETL pipeline. In particular, along with data **transformation**, you'll start setting up the components needed to communicate with the database.
- [x] Let's talk with the database
- [x] SQLAlchemy core components
- [x] Engines and sessions
- [x] Database tables
- [x] Table class definition
- [x] Columns definition
- [x] Data cleaning
- [x] Lower string and date format
- [x] Price and description
- [x] Put transform operations together
- [x] Setup base script
- [x] Create tables
- [x] Transform 'em all!

**3. From raw to clean data**
This chapter is all about moving transformed data to a clean table, from which insights can be built. You'll explore how to create a unique key to perform insert and delete statements on SQLAlchemy. At the end of this chapter you'll complete the **load** process, the last step of the ETL pipeline.
- [x] Unique key definition and clean table
- [x] Date data type definition
- [x] Unique key definition
- [x] Insert and delete operations
- [x] Querying
- [x] Insert and delete
- [x] Put load operations together
- [x] Insert operation
- [x] Delete operation
- [x] Load 'em all!

**4. From clean data to meaningful insights**
This chapter will show you how the data the ETL pipeline processes every month is used to build **insights**, readable by the fund’s shareholders. You'll explore key SQL components to build more complex queries and create these insights. You'll also explore libraries that will translate raw SQL queries into more readable Excel files.
- [x] Operators
- [x] Sales for Dublin and Cork
- [x] First month 2021 sales
- [x] Sqlalchemy func
- [x] Aggregate functions
- [x] Average, max and min functions
- [x] Create the insights
- [x] Creating the insights view
- [x] How many counties?
- [x] Working with Excel files
- [x] Create a simple Excel file
- [x] Add a table into Excel file
- [x] Export monthly insights
- [x] Wrap-up

**Comment by nanipumpkin** [comment]
[etl_python.pdf](https://github.com/saibrotech/mentoria/files/9931367/etl_python.pdf)

**Comment by piantino** [comment]
@nanipumpkin compartilhe no Discord a sua conquista!
