### ISSUE TITLE
Fazer simulado para Badge HTML

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#50]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes

Esta tarefa consiste em realizar os exercícios preparatórios para o exame de proficiência em HTML do LinkedIn.

**Comment by PaulaBuitoni** [comment]
Ja conseguimos a Badge de HTML

**Comment by AndreBuitoni** [comment]
Perfeito
