### ISSUE TITLE
Tentar Badge HTML no Linkedin

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#52]
Tentar [badge no linkedin](https://www.linkedin.com/skill-assessments/hub/quizzes/)

- [x] André Buitoni
- [x] Paula Buitoni

Reposítório com prática de exercícios
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/html/html-quiz.md

- [x] André Buitoni
- [x] Paula Buitoni

**Comment by AndreBuitoni** [comment]
Conquistei a minha Badge HTML!
![Image](https://github.com/saibrotech/mentoria/assets/68255266/37181e57-93c2-47b4-a3fa-559b8845aa7f)

**Comment by PaulaBuitoni** [comment]
Conquistei a minha Badge HTML! :D

![Image](https://github.com/saibrotech/mentoria/assets/68255632/9de8a3f6-31ba-435c-a9bb-abab208378b8)

**Comment by piantino** [comment]
Muito bom!
