### ISSUE TITLE
Fazer atividades do AVA do Floripa Mais Tech

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#54]
Conteúdo do Ambiente Virtual de Aprendizagem
https://ava.lab365.tech/login/index.php

- [x] Introdução
- [x] Módulo 1 - HTML
- [x] Módulo 2 - CSS

**Comment by PaulaBuitoni** [comment]
Prova do módulo 2 feita com sucesso, nota 10 de 10. 

Esta era uma etapa de nivelamento, agora temos que esperar pra ver quais serão as próximas etapas.

**Comment by PaulaBuitoni** [comment]
Segue imagens, com os conteúdos de html e css fornecido pelo AVA.
 

![Image](https://user-images.githubusercontent.com/68255632/195216416-404437f5-a682-4fec-ad33-b2ddc913d936.png)
![Image](https://user-images.githubusercontent.com/68255632/195216417-2a9da3bc-9f7d-4c6b-b7bf-bcddcc9a8b72.png)
![Image](https://user-images.githubusercontent.com/68255632/195216418-7578783f-fcec-4c91-959d-cb28c05d96b3.png)

**Comment by PaulaBuitoni** [comment]
PDFs fornecidos pelo sistema. 

[Programação Front-end Conceitos iniciais.pdf](https://github.com/saibrotech/mentoria/files/9760315/Programacao.Front-end.Conceitos.iniciais.pdf)
[Programação Front-end Elementos importantes.pdf](https://github.com/saibrotech/mentoria/files/9760314/Programacao.Front-end.Elementos.importantes.pdf)
[Programação Front-end Folhas de estilo em cascata.pdf](https://github.com/saibrotech/mentoria/files/9760316/Programacao.Front-end.Folhas.de.estilo.em.cascata.pdf)
[Programação Front-end.pdf](https://github.com/saibrotech/mentoria/files/9760317/Programacao.Front-end.pdf)

**Comment by piantino** [comment]
Relacionada à #49
