### ISSUE TITLE
Fazer conteúdos do App "Hellow" #FloripaMaisTec

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#55]
Página CONTEÚDO

- [x] Nível 1 - Quem sou eu?
- [x] Nível 1 - Lona e a Programação
- [x] Nível 1 - Nas teias da Internet

- [x] Nível 2 - Primeiros passos: O HTML!
- [x] Nível 2 - Elementos no HTML
- [x] Nível 2 - Estilizando textos com CSS
- [x] Nível 2 - Alinhamentos com CSS

- [x] Nível 3 - Guardando coisas em variáveis
- [x] Nível 3 - Interação com usuário
- [x] Nível 3 - Conversando com o HTML
- [x] Nível 3 - Conversando com o CSS

- [x] Nível 4 - Manipulando variáveis numéricas
- [x] Nível 4 - Manipulando Strings
- [x] Nível 4 - Testando Condições

- [x] Nível 5 - Trabalhando com Funções
- [x] Nível 5 - Trabalhando com Listas
- [x] Nível 5 - Trabalhando com Laços

Página DESAFIOS

- [x] Ilha Foods
- [x] Softplan
- [x] Mundo Dev
- [x] Ilha Acate
- [x] Mundo Tec
- [x] JS Island
- [x] Empreender

**Comment by PaulaBuitoni** [comment]
Tarefa terminada, achei 6/10... ele da uma ideia das coisas, mas não se aprofunda em nada.

**Comment by piantino** [comment]
Show Paulinha, continue assim!
