### ISSUE TITLE
Fazer curso de Figma no Dio (certificado)

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#56]
Será necessário criar uma conta para localizar o curso.
https://web.dio.me/course/introducao-pratica-ao-figma/

- [x] Capítulo 1 - Compreendendo a Ferramenta Figma
- [x] Capítulo 2 - Instalação e Assinatura do Figma
- [x] Capítulo 3 - Conhecendo a Interface do Figma
- [x] Capítulo 4 - Ferramentas da Área de Trabalho
- [x] Fazer teste
- [x] Obter Certificado
- [x] Colocar certificado no LinkedIn

Se desejar, poderá também realizar o mini-curso (1h27) do Gabriel Silvestri: 
#44

**Comment by AndreBuitoni** [comment]
Curso finalizado.
![Image](https://user-images.githubusercontent.com/68255266/218804684-eee4a2cd-374e-489e-8851-7907ded3d134.png)

**Comment by piantino** [comment]
@AndreBuitoni não esqueça de colocar o certificado no LinkedIn.

**Comment by AndreBuitoni** [comment]
Adicionado ao Linkedin

![Image](https://user-images.githubusercontent.com/68255266/222414591-d2faa143-d574-4708-a822-39d58372a9d3.png)
