### ISSUE TITLE
Curso Esri: Spatial Data Science: The New Frontier in Analytics

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#57]
[MOOC - Spatial Data Science: The New Frontier in Analytics](https://www.esri.com/training/catalog/5d76dcf7e9ccda09bef61294/spatial-data-science%3A-the-new-frontier-in-analytics/)

Registered on: 27/04/2022
Starts: 05/10/2022
Ends: 16/11/2022

Duration: 6 weeks (2-3 hours study per week)
Cost: Free

- [x] Introduction to Spatial Data Science
- [x] The Spatial Approach to Predictive Analysis
- [x] Finding Optimal Locations Using Suitability Models
- [x] Pattern Detection and Clustering
- [x] Object Detection with Deep Learning
- [x] Communicating Results with Impact

**Comment by nanipumpkin** [comment]
[Spatial Data Science_ The New Frontier in Analytics_Certificate_11182022.pdf](https://github.com/saibrotech/mentoria/files/10045616/Spatial.Data.Science_.The.New.Frontier.in.Analytics_Certificate_11182022.pdf)

**Comment by piantino** [comment]
Parabéns
