### ISSUE TITLE
Testar Penpot

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#59]
Testar a ferramenta Penpot para criação de protótipos e outros projetos criativos.
https://penpot.app/

- [x] Download e teste inicial
- [x] Usar por algum tempo
- [x] Avaliar se deseja fazer algum curso

**Comment by AndreBuitoni** [comment]
- Não foi necessário download, funciona no browser. Somente prexisa fazer log in.
- Utilizei, mas achei o Figma melhor. Esse é um pouco mais lento e tem um pouco menos ferramentas.
- Não farei curso desta ferramenta no momento.

**Comment by AndreBuitoni** [comment]
Criei uma garrafinha no tutorial do penpot =D

![Image](https://user-images.githubusercontent.com/68255266/218814840-65acb123-9024-466c-bdd2-3184c4f6f640.png)

**Comment by piantino** [comment]
Obrigado por testar @AndreBuitoni
