### ISSUE TITLE
Fazer processo seletivo Santander Code 2022

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#6]
https://letscode.com.br/processos-seletivos/santander-coders

### Etapas
- [x] Realizar inscrição para "Web Full Stack"
- [x] Fazer curso online - 26/08
- [x] Fazer teste de Lógica - 21/09
- [ ] Participar de Dinâmica com especialistas - 14/09
- [ ] Realizar coding Tank - 27/09
- [ ] Verificar resultado - 14/10

**Comment by IvanCarlosJr** [comment]
[Logica_Lista_de_exercicios.pdf](https://github.com/saibrotech/mentoria/files/9607357/Logica_Lista_de_exercicios.pdf)



[E-book_de_Logica.pdf](https://github.com/saibrotech/mentoria/files/9607360/E-book_de_Logica.pdf)

**Comment by piantino** [comment]
Não foi aprovado no teste lógica com programação Java.
