### ISSUE TITLE
Apresentar Tech Talk - Prototipagem e Figma

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#60]
Passos para apresentação do Tech Talk - Prototipagem e Figma

- [x] Definir Tema - Prototipagem e Figma
- [x] Agendar Data - 04/nov/2022
- [x] Preparar Tech Talk
- [x] Apresentar Tech Talk

**Comment by piantino** [comment]
Apresentação e Vídeo:
https://drive.google.com/drive/folders/1cOxmJvCXoEMAsOAYUobE0yrMGRVWaGIn?usp=share_link
