### ISSUE TITLE
Criar cronograma de Tech Talk

### ISSUE THREAD

**Issue by Nibuitoni** [saibrotech/mentoria#61]
- [x] Repassar material de Tech Talk: planilhas e vídeos
- [x] Ordenar cronograma
- [x] Cadastrar eventos no Discord

**Comment by Nibuitoni** [comment]
[Planilha](https://docs.google.com/spreadsheets/d/1Vg8bwLcB_hUzQqrl37vKMPm8mFkHzymyTlyi3SXym5Q/edit#gid=0) com sugestão de temas e proposta de datas.

**Comment by piantino** [comment]
Imagem para o evento do Discord:

![Image](https://user-images.githubusercontent.com/737364/194544438-0faae8b4-e21e-46ca-b20f-bc40f40601c8.jpg)

**Comment by piantino** [comment]
Verificado que todos os eventos foram criados no Discord.
