### ISSUE TITLE
Tentar Badge HTML no LikedIn

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#63]
Reposítório com prática de exercícios
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/html/html-quiz.md

**Comment by IvanCarlosJr** [comment]
https://www.linkedin.com/in/ivan-carlos-duarte-junior/

**Comment by piantino** [comment]
Parabéns Ivan, continue assim.
