### ISSUE TITLE
Apresentar Tech Talk sobre ETL

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#64]
Relacionado com:

- #47 
- https://github.com/saibrotech/mentorship-data-science

**Comment by nanipumpkin** [comment]
https://docs.google.com/presentation/d/1Hy6G2KotB_PnpflJQm9NwWnqeMuDvJzAFrLR9NGkQs0/edit?usp=share_link

**Comment by piantino** [comment]
Vìdeo original:
https://drive.google.com/drive/folders/1ZM2vcoXNT0j5wlwLlepU68Btimjk6_US

**Comment by piantino** [comment]
@AndreBuitoni fazer upload do vídeo para o Youtube

**Comment by piantino** [comment]
Show @AndreBuitoni já repostei na SaibroTech.
