### ISSUE TITLE
Participar das aulas práticas "Construa um Design System do Figma ao React"

### ISSUE THREAD

**Issue by PaulaBuitoni** [saibrotech/mentoria#65]
https://lp.rocketseat.com.br/inscricao/ignite-lab

- [x] Aula 0 - Ignite Lab, Do Figma ao React
- [x] Aula 1 - Estrutura Visual do Design System
- [ ] Aula 2 - Do Figma ao React, Criando a Aplicação
- [ ] Aula 3 - Testando e Automatizando
- [ ] Aula Extra - After Ignite Lab
- [ ] Se disponível, obter certificado
- [ ] Postar resultado no GitHub (portfolio)

**Comment by AndreBuitoni** [comment]
Hoje, durante a AULA 1 do mini-curso, criamos um design no Figma de uma tela de login. Na sequência iniciamos um projeto de Design System, onde padronizamos as cores, tamanhos de textos e de cabeçalhos, botões e outros componentes.

![Image](https://user-images.githubusercontent.com/68255266/195215035-68313eca-48ff-4b43-8743-c24806a76899.png)
![Image](https://user-images.githubusercontent.com/68255266/195215038-16c8d484-87ae-4512-8d82-37c505610f36.png)
![Image](https://user-images.githubusercontent.com/68255266/195215036-b6db31d8-8fc5-406f-b1db-d5131c2fad9a.png)

**Comment by PaulaBuitoni** [comment]
Igualmente ao André, segue minhas imagens!

![Image](https://user-images.githubusercontent.com/68255632/195215351-d99df6a2-2064-400d-b04a-ae21f2d6e574.png)
![Image](https://user-images.githubusercontent.com/68255632/195215352-0bf7a978-ca04-4d5e-bde6-69bafdb933e3.png)
![Image](https://user-images.githubusercontent.com/68255632/195215353-e48b583a-d582-44d5-9f66-36138efa0b08.png)

**Comment by piantino** [comment]
Está ficando muito bem galera!

**Comment by AndreBuitoni** [comment]
ATUALIZAÇÃO DE STATUS DA TAREFA

1. Nós tínhamos deixado essa tarefa para depois porque ainda não tínhamos noção de React, mas agora acho que já consigo terminar esse mini curso.
2. Salvamos os vídeos em algum lugar, pois somente ia ficar disponível online por 3 dias. Vou tentar localizar o curso nessa próxima semana. Se eu encontrar, vou tentar realizar essa semana. Se eu não encontrar os vídeos, já venha aqui dar a tarefa como desistida.

FIM DE ATUALIZAÇÃO DO STATUS

**Comment by AndreBuitoni** [comment]
Localizamos as AULAS 2 e 3.

Vou tentar seguir elas ao longo da semana!

**Comment by AndreBuitoni** [comment]
Tentei seguir a AULA 2, mas infelizmente encontrei muitos erros durante o projeto e não consegui dar andamento ao curso, vou ter que abandonar este curso.

**Comment by piantino** [comment]
Combinado em conjunto tentar resolver os problemas para continuar o curso (Liveshare).

**Comment by PaulaBuitoni** [comment]
infelizmente vou abandonar esse curso, pelos seguintes motivos:
1- Muitos erros no projeto, fazendo com que ele demande muito mais tempo que o planejado.
2- Não é meu foco de estudo no momento, Já que nem JS eu vi ainda.
3- Minha prioridade é terminar o do Guanabara.
4- Muitas atividades em aberto.

**Comment by AndreBuitoni** [comment]
Também vou abondanar essa tarefa para focar mais em outras mais relevantes.

**Comment by piantino** [comment]
Uma pena que não deu certo.
