### ISSUE TITLE
Fazer Capítulos do Bootstrap no Curso da Udemy Dr.Angela Yu

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#66]
Fazer as seções 6 e 7 do curso [The Complete 2022 Web Development Bootcamp](https://www.udemy.com/course/the-complete-web-development-bootcamp/)

- [x] ------ Seção 6 - Introduction to Bootstrap 4 ------
- [x] 6.1 - What is Bootstrap?
- [x] 6.2 - Installing Bootstrap
- [x] 6.3 - Web Design 101 - Wireframing
- [x] 6.4 - The Bootstrap Navigation bar
- [x] 6.5 - What we'll make: TinDog
- [x] 6.6 - Download the Starting Files
- [x] 6.7 - Setting up our new Project
- [x] 6.8 - Bootstrap Grid Layout System
- [x] 6.9 - Getting Montserrat Black and other font weights
- [x] 6.10 - Adding Grid Layouts to our website
- [x] 6.11 - A note about CSS link order
- [x] 6.12 - Bootstrap Containers
- [x] 6.13 - Bootstrap Buttons and Font Awesome
- [x] 6.14 - Styling our website Challenges and Solutions
- [x] 6.15 - Bootstrap Challenge 1
- [x] 6.16 - Solution to Bootstrap Challenge 1
- [x] 6.17 - Tip From Angela - How to Deal With Procrastination
- [ ] Seção 7 - Intermediate Bootstrap
- [x] 7.1 - The Bootstrap Carousel | Part 1
- [x] 7.2 - The Bootstrap Carousel | Part 2
- [x] 7.3 - Bootstrap Cards
- [x] 7.4 - The CSS Z-index and Stacking Order
- [x] 7.5 -  Media Query Breakpoints
- [x] 7.6 -  Bootstrap Chalenge 2
- [x] 7.7 - Bootstrap Chalenge 2 | Solution
- [x] 7.8 - How to Become a Better Programmer | Code Refactoring
- [x] 7.9 - Put it into Practice - Refactor our Website Part 1
- [x] 7.10 - Advanced CSS - Selector Priority
- [x] 7.11 - Completing the Website
- [x] 7.12 - Download the Completed Website
- [x] 7.13 - Tip From Angela - Building a Programming Habit
- [x] Se houver, postar resultado prático da atividade

---------

Seção 6 - Introduction to Bootstrap 4
![Image](https://user-images.githubusercontent.com/68255266/195219639-eabdd90d-ddc0-4264-bd91-fee6c8d99411.png)

Seção 7 - Intermediate Bootstrap
![Image](https://user-images.githubusercontent.com/68255266/195219715-5e2d4c6b-68fa-48b0-8ac9-f55911c69b22.png)

**Comment by AndreBuitoni** [comment]
Aqui está o website que fiz nestes dois capítulos, utilizando Bootstrap:
https://andrebuitoni.github.io/project-tindog/

O objetivo foi entender e praticar o uso do Bootstrap e das Media Queries. O site do TinDog é responsivo para 3 formatos diferentes: desktop, tablet e celular.

**Comment by piantino** [comment]
Coloquei a captura de tela para registrar o resultado, parabéns:

![Image](https://user-images.githubusercontent.com/737364/197759163-33476650-36f1-4542-9a03-da4a55f059a2.png)
