### ISSUE TITLE
Apresentar Tech Talk Lean

### ISSUE THREAD

**Issue by PaulaBuitoni** [saibrotech/mentoria#68]
https://docs.google.com/presentation/d/1NA06nHYLAu9Z4JI64Nn0Ayyy0WE28NGJ_8APwh3AZmo/edit#slide=id.p

**Comment by nanipumpkin** [comment]
Oi Paulinha, segue o material que te falei... É de um curso que fiz na pós de Engenharia de Produção.  Tem duas apresentações mais introdutorias, e uns livros do Mike Rother sobre método toyota/lean. São um pouco feiosos, mas o conteúdo pode ser útil...  
Por alguma razão não consegui fazer upload aqui, por isso to compartilhando meu [drive](https://drive.google.com/drive/folders/1do01tzwK60m11b0YZ2gPIILjevqR6vsy?usp=sharing)

Abraço,

**Comment by piantino** [comment]
Vídeo: https://drive.google.com/file/d/1EVTvHDsQxBlVQnd2ewC6HQCPYcIm7GPr/view?usp=sharing

**Comment by piantino** [comment]
Publicado no youtube, como não listado:
https://youtu.be/gj-bB26iC50
