### ISSUE TITLE
Apresentar Tech Talk sobre React/Next

### ISSUE THREAD

**Issue by gutivalente** [saibrotech/mentoria#70]
## Links úteis

https://www.freecodecamp.org/news/learn-react-basics-in-10-minutes/

## Apresentação

1. O que é React (2min)
2. Por que usar React (3min)
3. Principais recursos do React (10min)
4. O que é Next.js (2min)
5. Por que usar Next.js (2min)
6. Principais recursos do Next.js (3min)

1_________2_______________3_________________________________________________4_______5_________6_____________

**Comment by piantino** [comment]
Apresentação realizada e vídeo bruto salvo no drive:
https://drive.google.com/file/d/1hjb9z3hYvEoEsPYqOZfOD6uos2OebKfF/view?usp=share_link

Parabéns @gutivalente, fiquei contente de perceber o quanto já evoluiu e já domina da linguagem javascript.
