### ISSUE TITLE
Atualizar portfólio pessoal

### ISSUE THREAD

**Issue by gutivalente** [saibrotech/mentoria#71]
https://gutivalente.github.io/

**Comment by gutivalente** [comment]
https://github.com/gutivalente/gutivalente.github.io/commit/eb31f1dea45558f05e13aed609036fe3bf840823

**Comment by piantino** [comment]
Muito bom Gu, só faltou a data de finalização da experiência na SaibroTech.

**Comment by gutivalente** [comment]
Achei que tivesse feito isso, devo ter esquecido. Fiz um amend
https://github.com/gutivalente/gutivalente.github.io/commit/28425723c5efa0a8bf96645be7a18728a9b4533b

**Comment by piantino** [comment]
Muito bom Gu!
