### ISSUE TITLE
Melhorar LinkedIn

### ISSUE THREAD

**Issue by nanipumpkin** [saibrotech/mentoria#72]
- [x] Ajustar cargo para analista de dados na Saibrotech;
- [x] Colocar o about em português quando a página estiver em português;
- [x] Adicionar voluntariado no Projeto novos caminhos

Relacionada à #29

**Comment by piantino** [comment]
Muito bom!

**Comment by piantino** [comment]
@nanipumpkin lembre se de colocar imagem do resultado da atividade aqui na tarefa, ajuda na revisão e é uma boa prática demonstrar o resultado.
