### ISSUE TITLE
Melhorar LinkedIn

### ISSUE THREAD

**Issue by Nibuitoni** [saibrotech/mentoria#74]
Itens de melhoria a partir da atividade #29 

- [ ] Adicionar tags
- [ ] Incluir featured com link de certificados
- [ ] Adicionar trabalho voluntário na Saibrotech
- [ ] Atualizar e incluir certificados

**Comment by piantino** [comment]
Olá,
Estou organizando as atividades do board, você ainda tem interesse nessa atividade?

**Comment by piantino** [comment]
@Nibuitoni estou encerrando essa atividade no nosso board.
