### ISSUE TITLE
Colocar vídeos das tech talks no youtube

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#78]
Tarefas

- [x] Criar Canal da SaibroTech
- [x] Criar seção SOBRE
- [x] Fazer upload das TechTalks em modo Unlisted e em Playlist "Tech Talks"
- [x] Adicionar editores André B / Paulinha
- [x] Adicionar imagem do Banner
- [x] Adicionar marca d'água nos vídeos
- [x] Adicionar links no SOBRE
- [x] Conseguir URL personalizada
- [x] Fazer a verificação de segurança pelo celular

**Comment by piantino** [comment]
Canal criado: https://www.youtube.com/channel/UCeWvy14IaeI_6awoOGubOOA

**Comment by piantino** [comment]
@AndreBuitoni e @PaulaBuitoni tem um novo recurso de identificador, criei o seguinte:

https://youtube.com/@saibrotech

**Comment by Nibuitoni** [comment]
Adicionados pleo @AndreBuitoni 2 vídeos no canal, sendo o de metodologia ágil público e o de Angular forms como unlisted.

**Comment by piantino** [comment]
Coloquei privado entre parênteses na frente da playlist para ficar mais claro:

![image](https://user-images.githubusercontent.com/737364/199259652-7290cc94-5a91-45f7-b88d-ec7b91794d99.png)

**Comment by AndreBuitoni** [comment]
Perfeito. Eu tentei alterar o nome mas o YouTube não permite que administradores alterem playlists... Mas podem criar... Vai entender!

**Comment by AndreBuitoni** [comment]
Acho que podemos dar essa tarefa como concluída. 

Quantos às próximas, talvez seja melhor criar uma tarefa separada para cada tech talk. Em geral o processo todo está levando umas 3h. Os principais processos estão sendo:

- download da gravação;
- edição do vídeo;
- exportação do vídeo editado;
- criação de thumbnail;
- upload para o YouTube;
- preenchimento de metadados;
- postagem;
- divulgação do link no linkedin.

Vou já criar uma tarefa para a postagem do vídeo do Ivan e colar essa lista de tarefas.
Abraços.

**Comment by piantino** [comment]
Muito bem planejado o check list das etapas, parabéns!
