### ISSUE TITLE
Fazer capítulos de JavaScript no curso da Angela Yu

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#79]
Esta é uma tarefa parcial da tarefa #77 

Capítulos de JavaScript:

- [x] Seção 9 -Introduction to JavaSript ES6 - (2h28)
- [x] 9.01 - Introduction to Javascript - (12min)
- [x] 9.02 - Javascript alerts - Adding Behaviour to Websites - (14min) 
- [x] 9.03- Data Types - (4min)
- [x] 9.04 - Javascript Variables - (10min)
- [x] 9.05 - Javascript Variables Exercise Start - (3min)
- [x] Exercício de Programação 2: Javascript Variables Exercise
- [x] 9.06 - Javascript Variables Exercise Solution (3min)
- [x] 9.07 - Naming and Naming Conventions for Javascript Variables (7min)
- [x] Teste 2: Javascript Variable Naming Quiz
- [x] 9.08 - String Concatenation (3min)
- [x] 9.09 - String Lengths and Retrieving the Number of Characters (6min)
- [x] 9.10 - Slicing and Extracting Parts of a String (9min)
- [x] 9.11 - Challenge: Changing Case in Text (4min)
- [x] 9.12 - Challenge: Changing String Casing Solution (9min)
- [x] 9.13 - Basic Arithmetic and the Modulo Operator in Javascript (6min)
- [x] 9.14 - Increment and Decrement Expressions (2min)
- [x] Teste 3: Javascript Numbers Quiz 
- [x] 9.15 - Functions Part 1: Creating and Calling Functions (11min)
- [x] 9.16 - Functions Part 1 Challenge - The Karel Robot (9min)
- [x] 9.17 - The Karel Chess Board Solution
- [x] 9.18 - A Quick Note About the next Lesson
- [x] 9.19 - Functions Part 2: Parameters and Arguments (10min)
- [x] Exercício de Programação 3: Life in Weeks Coding Exercise
- [x] 9.20 - Life in Weeks Solution (4min)
- [x] 9.21 - Functions Part 3 : Outputs & Return Values (11min)
- [x] 9.22 - Challenge: Create a BMI Calculator (2min)
- [x] Exercício de Programação 4: BMI Calculator Challenge
- [x] 9.23 - Challenge: BMI Calculator Solution (6min)
- [x] Teste 4: JavaScript Functions Quiz
- [x] 9.24 - Tip From Angela - Set Your Expectations (3min)
- [x] Postar resultados.
- [x] Seção 10 - Intermediate Javascript
- [x] 125 - Random Number Generation in Javascript: Building a Love Calculator (11min)
- [x] 126 - Control Statements: Using If-Else Conditionals & Logic (5min)
- [x] 127 - Comparators and Equality (3min)
- [x] 128 - Combining Comparators (3min)
- [x] Exercício de programação 5: BMI calculator advanced (if/else)
- [x] 129 - Introducing the Leap Year Code Challenge (4min)
- [x]  Exercício de programação 6 - Leap Year Challenge Exercise
- [x] 130 - Leap Year Solution (3min)
- [x] 131 - Collections: Working with Javascript Arrays (9min)
- [x] 132 - Adding Elements and Intermediate Array Techniques
- [x] Exercício de programação 7: Who's Buying Lunch? Code Challenge
- [x] 133 - Who's Buying Lunch Solution (4min)
- [x] 134 - Control Statements: While Loops (8min)
- [x] 135 - Solution to the 99 Bottles Challenge (1min)
- [x] 136 - Control Statement: For Loops (6min)
- [x] 137 - Introducing the Fibonacci Code Challenge (7min)
- [x] Exercício de programação 8: The Fibonacci Exercise
- [x] 138 - Fibonacci Solution (8min)
- [x] 139 - Tip From Angela - Retrieval is How You Learn (3min)

**Comment by AndreBuitoni** [comment]
Infelizmente não consegui resultado prático para postar.

**Comment by piantino** [comment]
Certo @AndreBuitoni, conforme conversamos vamos avaliar o próximo módulo para ver se vale continuar esse curso.
