### ISSUE TITLE
Fazer processo seletivo JaBrasil TI

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#8]
https://jabrasil.org.br/ti

Santa Catarina
Aulas: Aulas online e ao vivo. Exercícios e conteúdos na plataforma Coursera. Você precisará se dedicar 5 vezes por semana, 4 horas por dia. Início das aulas: 29.08 a 09.12
Número de Vagas: 20

- [x] Fazer inscrição
- [x] Enviar documentação necessária 
- [x] Participar dos encontros via Meet nos dias 22, 23 e 24 de agosto às 19h
- [x] Compartilhar certificado da semana experimental no LinkedIn
- [x] Aguardar resultado

**Comment by IvanCarlosJr** [comment]
https://www.linkedin.com/posts/ivan-carlos-duarte-junior_certificado-semana-experimental-techja-activity-6968919147791437824-SW-O?utm_source=share&utm_medium=member_desktop

**Comment by piantino** [comment]
A postagem ficou muito boa Ivan!
