### ISSUE TITLE
Verificar celular no YouTube

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#84]
Para poder fazer upload de vídeos com mais de 15 minutos no YouTube, é necessário vincular um celular com a conta do YouTube. #78 

Mais informações em: https://support.google.com/youtube/answer/71673?hl=pt-BR

Para realizar este procedimento, por favor siga os passos descritos em: https://www.youtube.com/verify

- [x] Celular Vinculado com Sucesso.

**Comment by piantino** [comment]
@AndreBuitoni celular verificado:

![Image](https://user-images.githubusercontent.com/737364/198396580-e8c61f7c-a254-4d71-89bc-d17f78865fab.png)
