### ISSUE TITLE
Analisar formas para estruturar uma preparação de um processo seletivo

### ISSUE THREAD

**Issue by Nibuitoni** [saibrotech/mentoria#91]
Ponto da retrospectiva de setembro - verificar formas de estruturar uma preparação para processos seletivos

**Comment by Nibuitoni** [comment]
Checklist com dicas e passos a serem seguidos para o processo seletivo

**Comment by Nibuitoni** [comment]
@IvanCarlosJr e @nanipumpkin se puderem dar uma lida no checklist e revisarem.

**Comment by nanipumpkin** [comment]
Acho que tá de acordo com o que eu tenho feito por aqui também. Eu só acrescentaria o seguinte:
- Preparar um currículo enxuto e legível (1, max. 2 pag.) montado no word/google docs, para poder atualizar conforme a necessidade de cada vaga e anexar em pdf nos processos seletivos. Aquele da ferramenta geradora de currículos do LinkedIn acaba ficando redundante, pois é um snapshot das mesmas coisas que vemos no link do perfil.
- Quando aplicar pra uma vaga, se houver um link de acesso externo no site da própria empresa, aplicar por esse link, pois ali geralmente tem formulários com perguntas específicas que geralmente não aparecem pelo processo automático do LinkedIn.

**Comment by IvanCarlosJr** [comment]
Acho que está muito bom, estou seguindo esses passos.

**Comment by piantino** [comment]
Ótimas colocações pessoal!
