### ISSUE TITLE
Apresentar Tech Talk sobre Redes

### ISSUE THREAD

**Issue by IvanCarlosJr** [saibrotech/mentoria#93]
https://docs.google.com/presentation/d/1HNwsFbgEkjqmmXSfQWrHhZTJBOWmSjP9vL61x8rokbk/edit#slide=id.g14cc9914b78_0_158

**Comment by piantino** [comment]
Parabéns pela apresentação Ivan.
O vídeo será postado no Youtube na atividade #95
