### ISSUE TITLE
Postar Vídeo da Tech Talk do Ivan no YouTube

### ISSUE THREAD

**Issue by AndreBuitoni** [saibrotech/mentoria#95]
Passos para concluir a tarefa:

- [x] download da gravação;
- [x] edição do vídeo;
- [x] exportação do vídeo editado;
- [x] criação de thumbnail;
- [x] upload para o YouTube;
- [x] preenchimento de metadados;
- [x] postagem;
- [x] divulgação do link no linkedin.

**Comment by piantino** [comment]
Vídeo bruto:
https://drive.google.com/file/d/1yx8hXfr1eycuVkpwiPN8OMT3RgpuSJuS/view?usp=share_link

**Comment by AndreBuitoni** [comment]
Online!
https://www.youtube.com/watch?v=z2IAH6MjRBM

**Comment by piantino** [comment]
Show @AndreBuitoni já repostei na SaibroTech:
https://www.linkedin.com/posts/saibrotech_redes-e-modelo-osi-tech-talks-saibrotech-activity-6999482007382552576-JHDi?utm_source=share&utm_medium=member_desktop
